In [1]:
import pandas as pd 
df=pd.read_csv("sales_data_raw.csv")
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185

In [2]:
df.describe()

           OrderID    Quantity    UnitPrice   CustomerID    TotalAmount
count   515.000000  515.000000   515.000000   515.000000     515.000000
mean   1250.603883   12.106796   463.097087  5104.452427    5089.194175
std     143.913487   20.056201   466.886482    56.813498   11867.721283
min    1001.000000    1.000000    19.000000  5001.000000      19.000000
25%    1124.500000    5.000000    49.000000  5057.500000     418.000000
50%    1252.000000   10.000000   299.000000  5108.000000    1343.000000
75%    1374.500000   14.500000   899.000000  5153.500000    6589.000000
max    1500.000000  181.000000  1299.000000  5200.000000  187056.000000

In [3]:
df.head(5)

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196

In [4]:
df.isnull().sum()

OrderID           0
Date              0
Region           10
Product           0
Category          0
Quantity          0
UnitPrice         0
CustomerID        0
SalesRep         10
PaymentMethod     5
TotalAmount       0
dtype: int64

In [5]:
df['Region'].fillna('Unknown',inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15236\784993391.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Region'].fillna('Unknown',inplace=True)

In [6]:
df['Region'].isnull().sum()

np.int64(0)

In [7]:
df['SalesRep'].fillna('Unknown',inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15236\2502912724.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SalesRep'].fillna('Unknown',inplace=True)

In [8]:
df['SalesRep'].isnull().sum()

np.int64(0)

In [9]:
Payment=df['PaymentMethod'].mode()[0]

In [10]:
df['PaymentMethod'].fillna(Payment,inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_15236\4215254032.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PaymentMethod'].fillna(Payment,inplace=True)

In [11]:
df['PaymentMethod'].isnull().sum()

np.int64(0)

In [16]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
510    False
511    False
512    False
513    False
514    False
Length: 515, dtype: bool

In [17]:
df.duplicated().sum()

np.int64(13)

In [15]:
df[df.duplicated()]

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
101,1105,2024-06-11,East,Headphones,Accessories,4,299,5176,Alice,Net Banking,1196
182,1282,2024-03-15,Central,Keyboard,Electronics,14,1299,5162,Charlie,Credit Card,18186
199,1111,2024-05-14,North,Charger,Electronics,12,79,5128,Diana,Credit Card,948
275,1123,2024-08-01,South,Mouse,Electronics,12,1299,5147,Charlie,Cash,15588
332,1066,2024-04-15,North,Headphones,Electronics,12,599,5152,Eve,Net Banking,7188
361,1425,2024-11-06,West,Tablet,Accessories,7,79,5061,Bob,Cash,553
406,1280,2024-06-09,North,Mouse,Accessories,3,599,5158,Bob,Credit Card,1797
458,1319,2024-08-13,North,Tablet,Electronics,13,79,5161,Charlie,Credit Card,1027
482,1314,2024-12-30,Central,Mouse,Accessories,4,299,5076,Eve,Debit Card,1196
490,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
494,1309,2024-01-22,West,Headphones,Accessories,13,1299,5194,Bob,Net Banking,16887
499,1100,2024-05-08,Central,Mouse,Accessories,2,49,5127,Bob,UPI,98
507,1185,2024-06-13,North,Mouse,Electronics,5,1299,5032,Alice,UPI,6495

In [26]:
Data=df.drop_duplicates().reset_index(drop=True)

In [27]:
Data

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
...,...,...,...,...,...,...,...,...,...,...,...
497,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596
498,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093
499,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735
500,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147
501,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185

In [29]:
Data.duplicated().sum()

np.int64(0)

In [35]:
df['Product'].str.strip().str.title().reset_index()

     index     Product
0        0       Phone
1        1       Phone
2        2      Laptop
3        3      Laptop
4        4    Keyboard
..     ...         ...
510    510  Headphones
511    511  Headphones
512    512      Tablet
513    513       Phone
514    514      Laptop

[515 rows x 2 columns]

In [36]:
df['Region'].str.title().reset_index()

     index   Region
0        0    North
1        1  Central
2        2     West
3        3    North
4        4    North
..     ...      ...
510    510    North
511    511     East
512    512     East
513    513  Central
514    514    South

[515 rows x 2 columns]

In [39]:
quantity_mean=df['Quantity'].mean()

In [40]:
quantity_std=df['Quantity'].std()

In [41]:
quantity_mean

np.float64(12.106796116504855)

In [42]:
quantity_std

20.056201492665096

In [43]:
df['Outlier_mask']=df['Quantity']>(quantity_mean+(3*quantity_std))

In [44]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,False
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,False
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,False
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,False
...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,False
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,False
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,False
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,False
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,False

In [61]:
df.sort_values(by="Outlier_mask")

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Month,Year,HighValue
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False,7,2024,False
346,1222,2024-11-19,Unknown,Tablet,Accessories,8,299,5171,Eve,Credit Card,2392,False,11,2024,False
345,1437,2024-04-01,West,Charger,Accessories,12,79,5187,Eve,Cash,948,False,4,2024,False
344,1411,2024-02-23,Central,Tablet,Electronics,7,299,5028,Diana,Net Banking,2093,False,2,2024,False
343,1143,2024-02-21,East,Keyboard,Accessories,1,19,5098,Frank,Cash,19,False,2,2024,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1373,2024-06-24,West,Tablet,Accessories,181,79,5145,Alice,Net Banking,14299,True,6,2024,False
395,1327,2024-01-04,Central,Tablet,Accessories,175,19,5058,Frank,Cash,3325,True,1,2024,False
216,1249,2024-05-07,Central,Headphones,Accessories,173,899,5109,Diana,Credit Card,155527,True,5,2024,True
84,1040,2024-08-31,West,Headphones,Accessories,165,49,5049,Eve,Credit Card,8085,True,8,2024,False
462,1320,2024-10-03,East,Headphones,Accessories,162,79,5163,Charlie,Cash,12798,True,10,2024,False

In [49]:
product_median=df.groupby('Product')['Quantity'].transform('median')

In [51]:
product_median

0       9.5
1       9.5
2      10.0
3      10.0
4      10.0
       ...
510    12.0
511    12.0
512     9.5
513     9.5
514    10.0
Name: Quantity, Length: 515, dtype: float64

In [52]:
df['Date']=pd.to_datetime(df['Date'])

In [54]:
df['Month']=df['Date'].dt.month

In [55]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Month
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False,7
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,False,10
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,False,11
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,False,11
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,False,6
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,False,9
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,False,8
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,False,10
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,False,5

In [56]:
df['Year']=df['Date'].dt.year

In [57]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Month,Year
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False,7,2024
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,False,10,2024
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,False,11,2024
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,False,11,2024
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,False,2,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,False,6,2024
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,False,9,2024
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,False,8,2024
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,False,10,2024
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,False,5,2024

In [58]:
df['HighValue']=df['TotalAmount']>df['TotalAmount'].quantile(0.95)

In [62]:
df.sort_values(by="HighValue")

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Month,Year,HighValue
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False,7,2024,False
347,1096,2024-12-10,West,Tablet,Accessories,17,899,5178,Frank,Debit Card,15283,False,12,2024,False
346,1222,2024-11-19,Unknown,Tablet,Accessories,8,299,5171,Eve,Credit Card,2392,False,11,2024,False
345,1437,2024-04-01,West,Charger,Accessories,12,79,5187,Eve,Cash,948,False,4,2024,False
344,1411,2024-02-23,Central,Tablet,Electronics,7,299,5028,Diana,Net Banking,2093,False,2,2024,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,1075,2024-12-16,East,Phone,Electronics,19,1299,5163,Unknown,UPI,24681,False,12,2024,True
170,1235,2024-07-19,East,Laptop,Electronics,16,1299,5055,Bob,Cash,20784,False,7,2024,True
286,1311,2024-06-06,South,Charger,Accessories,16,1299,5108,Eve,UPI,20784,False,6,2024,True
451,1014,2024-12-25,East,Laptop,Accessories,15,1299,5103,Alice,Debit Card,19485,False,12,2024,True
252,1372,2024-09-02,East,Charger,Electronics,19,1299,5142,Eve,Debit Card,24681,False,9,2024,True

In [66]:
df.groupby(['Region','Product']).agg({'TotalAmount':['sum','mean']})

                       TotalAmount
                               sum          mean
Region  Product
Central   Keyboard             152    152.000000
          Laptop              3294   1647.000000
        Charger              44778   4070.727273
        Headphones          217647  21764.700000
        Keyboard            117858   5124.260870
        Laptop               47034   3135.600000
        Mouse                28375   1576.388889
        Phone                43545   4354.500000
        Tablet              116059   6108.368421
East      Headphones          7192   7192.000000
          Laptop               209    209.000000
        Charger              51966   4724.181818
        Headphones           56571   4714.250000
        Keyboard             55763   3485.187500
        Laptop               68049   5670.750000
        Mouse                19269   1926.900000
        Phone                96420   5671.764706
        Tablet               31165   2397.307692
North     Headphones          4792   4792.000000
        Charger             121229   5510.409091
        Headphones           53409   3814.928571
        Keyboard             49328   3523.428571
        Laptop               43505   3346.538462
        Mouse               255462  19650.923077
        Phone               119319   5965.950000
        Tablet               10261   1026.100000
South     Laptop              2093   2093.000000
        Charger              67862   4524.133333
        Headphones           51158   6394.750000
        Keyboard             30960   3440.000000
        Laptop               66380   3687.777778
        Mouse                88132   5508.250000
        Phone               102281   7305.785714
        Tablet               94206   7246.615385
Unknown Charger               5196   5196.000000
        Keyboard              4035   2017.500000
        Laptop                5622   2811.000000
        Mouse                 9584   9584.000000
        Phone                18875   9437.500000
        Tablet                3691   1845.500000
West      Headphones         14289  14289.000000
          Laptop                98     98.000000
          Phone               5391   5391.000000
        Charger              43321   4332.100000
        Headphones           87450   5830.000000
        Keyboard             36059   3004.916667
        Laptop               36304   3300.363636
        Mouse                41473   2764.866667
        Phone                29631   3703.875000
        Tablet               81822   4545.666667
central Keyboard               882    882.000000
        Laptop                 228    228.000000
        Mouse                 5394   2697.000000
east    Laptop                 294    294.000000
        Phone                  152    152.000000
north   Mouse                 1198   1198.000000
south   Charger               1798   1798.000000
west    Laptop               22083  22083.000000
        Tablet                 342    342.000000

In [79]:
sales=df.groupby(['Month','Product']).agg({'Quantity':'sum'})

In [83]:
best_selling_product = sales.loc[sales.groupby(['Month'])['Quantity'].idxmax()]

In [84]:
best_selling_product

                  Quantity
Month Product
1     Tablet           197
2     Keyboard          85
3     Keyboard          63
4     Mouse            131
5     Headphones       247
6     Tablet           264
7     Keyboard          87
8     Tablet           284
9     Phone            157
10    Headphones       197
11    Keyboard         195
12    Tablet           103

In [90]:
pivot_table_example = pd.pivot_table(df, 
                                     values='TotalAmount', 
                                     index='Region', 
                                     columns='Product', 
                                     aggfunc='sum', 
                                    fill_value=0)

In [91]:
pivot_table_example

Product,Headphones,Keyboard,Laptop,Phone,Charger,Headphones,Keyboard,Laptop,Mouse,Phone,Tablet
Region,,,,,,,,,,,
Central,0,152,3294,0,44778,217647,117858,47034,28375,43545,116059
East,7192,0,209,0,51966,56571,55763,68049,19269,96420,31165
North,4792,0,0,0,121229,53409,49328,43505,255462,119319,10261
South,0,0,2093,0,67862,51158,30960,66380,88132,102281,94206
Unknown,0,0,0,0,5196,0,4035,5622,9584,18875,3691
West,14289,0,98,5391,43321,87450,36059,36304,41473,29631,81822
central,0,0,0,0,0,0,882,228,5394,0,0
east,0,0,0,0,0,0,0,294,0,152,0
north,0,0,0,0,0,0,0,0,1198,0,0
south,0,0,0,0,1798,0,0,0,0,0,0
west,0,0,0,0,0,0,0,22083,0,0,342

In [93]:
a=df.groupby('SalesRep')['TotalAmount'].sum().idxmax()

In [94]:
a

'Charlie'

In [95]:
a=df.groupby('SalesRep')['TotalAmount'].sum()

In [96]:
a

SalesRep
Alice      368308
Bob        317880
Charlie    516371
Diana      472319
Eve        406726
Frank      472463
Unknown     66868
Name: TotalAmount, dtype: int64

In [97]:
salesrep_revenue = df.groupby('SalesRep')['TotalAmount'].sum() 
top_salesrep = salesrep_revenue.idxmax() 
print(top_salesrep, salesrep_revenue[top_salesrep])

Charlie 516371

In [98]:
top3_orders = df.groupby('SalesRep')['OrderID'].count().nlargest(3)

In [100]:
top3_orders.reset_index()

  SalesRep  OrderID
0  Charlie       94
1      Eve       93
2    Alice       83