## import a car.csv dataset.- Filter top-performing products.- Save clean data as filtered_sales.csv

In [3]:
import pandas as pd
df=pd.read_csv("car.csv")
print(df)

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol
1        sx4  2013           4.75           9.54       43000    Diesel
2       ciaz  2017           7.25           9.85        6900    Petrol
3    wagon r  2011           2.85           4.15        5200    Petrol
4      swift  2014           4.60           6.87       42450    Diesel
..       ...   ...            ...            ...         ...       ...
296     city  2016           9.50          11.60       33988    Diesel
297     brio  2015           4.00           5.90       60000    Petrol
298     city  2009           3.35          11.00       87934    Petrol
299     city  2017          11.50          12.50        9000    Diesel
300     brio  2016           5.30           5.90        5464    Petrol

    Seller_Type Transmission  Owner
0        Dealer       Manual      0
1        Dealer       Manual      0
2        Dealer       Manual      0
3        Dealer       Manual      0
4        Dealer       Manual      0
..          ...          ...    ...
296      Dealer       Manual      0
297      Dealer       Manual      0
298      Dealer       Manual      0
299      Dealer       Manual      0
300      Dealer       Manual      0

[301 rows x 9 columns]

In [6]:
print(df.Kms_Driven)

0      27000
1      43000
2       6900
3       5200
4      42450
       ...
296    33988
297    60000
298    87934
299     9000
300     5464
Name: Kms_Driven, Length: 301, dtype: int64

In [14]:
most_kms_driven=df.sort_values(by='Kms_Driven', ascending=False)

In [24]:
most_kms_driven.to_excel("filtered_car_csv.xlsx")
df2=pd.read_excel("filtered_car_csv.xlsx")

In [27]:
df2

,Unnamed: 0,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,196,Activa 3g,2008,0.17,0.52,500000,Petrol,Individual,Automatic,0
1,179,Honda Karizma,2010,0.31,1.05,213000,Petrol,Individual,Manual,0
2,84,innova,2005,3.49,13.46,197176,Diesel,Dealer,Manual,0
3,85,camry,2006,2.50,23.73,142000,Petrol,Individual,Automatic,3
4,77,corolla,2004,1.50,12.35,135154,Petrol,Dealer,Automatic,0
...,...,...,...,...,...,...,...,...,...,...
296,173,Activa 4g,2017,0.40,0.51,1300,Petrol,Individual,Automatic,0
297,103,Bajaj Dominar 400,2017,1.45,1.60,1200,Petrol,Individual,Manual,0
298,166,Hero Passion Pro,2016,0.45,0.55,1000,Petrol,Individual,Manual,0
299,165,Activa 3g,2016,0.45,0.54,500,Petrol,Individual,Automatic,0
300,133,Bajaj Avenger 220,2016,0.72,0.95,500,Petrol,Individual,Manual,0

In [25]:
df1=df2.query('Transmission=="Manual"')
print(df1)

     Unnamed: 0            Car_Name  Year  Selling_Price  Present_Price  \
1           179       Honda Karizma  2010           0.31           1.05
2            84              innova  2005           3.49          13.46
6            37                 800  2003           0.35           2.28
8           200    Bajaj Pulsar 150  2006           0.10           0.75
9            54              innova  2005           2.75          10.21
..          ...                 ...   ...            ...            ...
294         101  UM Renegade Mojave  2017           1.70           1.82
295         126   Bajaj Avenger 220  2017           0.90           0.95
297         103   Bajaj Dominar 400  2017           1.45           1.60
298         166    Hero Passion Pro  2016           0.45           0.55
300         133   Bajaj Avenger 220  2016           0.72           0.95

     Kms_Driven Fuel_Type Seller_Type Transmission  Owner
1        213000    Petrol  Individual       Manual      0
2        197176    Diesel      Dealer       Manual      0
6        127000    Petrol  Individual       Manual      0
8         92233    Petrol  Individual       Manual      0
9         90000    Petrol  Individual       Manual      0
..          ...       ...         ...          ...    ...
294        1400    Petrol  Individual       Manual      0
295        1300    Petrol  Individual       Manual      0
297        1200    Petrol  Individual       Manual      0
298        1000    Petrol  Individual       Manual      0
300         500    Petrol  Individual       Manual      0

[261 rows x 10 columns]

In [26]:
df2.count()

Unnamed: 0       301
Car_Name         301
Year             301
Selling_Price    301
Present_Price    301
Kms_Driven       301
Fuel_Type        301
Seller_Type      301
Transmission     301
Owner            301
dtype: int64

In [23]:
df1.count()

Car_Name         261
Year             261
Selling_Price    261
Present_Price    261
Kms_Driven       261
Fuel_Type        261
Seller_Type      261
Transmission     261
Owner            261
dtype: int64

In [29]:
df3=df[df['Transmission']=="Manual"]

In [30]:
df3

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [37]:
df4=df.filter(items=['Transmission'])

In [38]:
df4

    Transmission
0         Manual
1         Manual
2         Manual
3         Manual
4         Manual
..           ...
296       Manual
297       Manual
298       Manual
299       Manual
300       Manual

[301 rows x 1 columns]

## filter with selling price greater than 5 and seller_type = dealer and kms_driven < 20000

In [42]:
filtered_df = df[(df['Selling_Price'] > 5) & (df['Seller_Type'] == 'Dealer')&(df['Kms_Driven'] < 20000)]

In [44]:
filtered_df.count()

Car_Name         33
Year             33
Selling_Price    33
Present_Price    33
Kms_Driven       33
Fuel_Type        33
Seller_Type      33
Transmission     33
Owner            33
dtype: int64

## Given a sales DataFrame with 'Date', 'Product', 'Revenue', calculate monthly total revenue.

In [14]:
import pandas as pd

In [15]:
salesData1 = {
'Date': pd.date_range(start='2025-01-01', periods=12, freq='W'),
'Product': ['A', 'B', 'C'] * 4,
'Revenue': [100, 200, 150, 120, 220, 130, 110, 180, 170, 115, 235, 175]
}

In [16]:
df = pd.DataFrame(salesData1)

In [17]:
df['Month'] = df['Date'].dt.to_period('M')

In [18]:
df

         Date Product  Revenue    Month
0  2025-01-05       A      100  2025-01
1  2025-01-12       B      200  2025-01
2  2025-01-19       C      150  2025-01
3  2025-01-26       A      120  2025-01
4  2025-02-02       B      220  2025-02
5  2025-02-09       C      130  2025-02
6  2025-02-16       A      110  2025-02
7  2025-02-23       B      180  2025-02
8  2025-03-02       C      170  2025-03
9  2025-03-09       A      115  2025-03
10 2025-03-16       B      235  2025-03
11 2025-03-23       C      175  2025-03

In [19]:
monthly_total = df.groupby('Month')['Revenue'].sum()
print(monthly_total)

Month
2025-01    570
2025-02    640
2025-03    695
Freq: M, Name: Revenue, dtype: int64

In [20]:
monthly_total = df.groupby('Month')['Revenue'].sum().reset_index()
print(monthly_total)

     Month  Revenue
0  2025-01      570
1  2025-02      640
2  2025-03      695

In [29]:
monthly_total = df.groupby('Month').agg({'Revenue':'sum'}).rename(columns={'Revenue':'TotalRevenue'})
print(monthly_total)

         TotalRevenue
Month
2025-01           570
2025-02           640
2025-03           695

## Data Wrangling

In [5]:
import pandas as pd

In [6]:
data = {'Name': ['Jai', 'Princi', 'Gaurav','Anuj', 'Ravi', 'Natasha', 'Riya'],'Age': [17, 17, 18, 17, 18, 17, 17],'Gender': ['M', 'F', 'M', 'M', 'M', 'F', 'F'],'Marks': [90, 76, 'NaN', 74, 65, 'NaN', 71]}

In [7]:
df=pd.DataFrame(data)

In [8]:
df   ## NaN-Not a Number- if a NaN is present you should solve with mean and median

      Name  Age Gender Marks
0      Jai   17      M    90
1   Princi   17      F    76
2   Gaurav   18      M   NaN
3     Anuj   17      M    74
4     Ravi   18      M    65
5  Natasha   17      F   NaN
6     Riya   17      F    71

In [9]:
import numpy as np

In [10]:
add=0
c=0
for i in df["Marks"]:
    if str(i).isnumeric():
        add=add+i
        c+=1
    else:
       continue

In [11]:
add

376

In [12]:
c

5

In [13]:
avg=round(add/c)

In [14]:
avg

75

In [17]:
df=df.replace(to_replace="NaN",value=avg)

In [18]:
df

      Name  Age Gender  Marks
0      Jai   17      M     90
1   Princi   17      F     76
2   Gaurav   18      M     75
3     Anuj   17      M     74
4     Ravi   18      M     65
5  Natasha   17      F     75
6     Riya   17      F     71