## ASSIGNMENT 2: NumPy for Numeric Data

## Q2.1: Array Creation and Shape

#### Load the regional performance data into NumPy arrays and display the shape and data types.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('assignment2_regional_performance(in).csv')
df

,RegionName,Q1Revenue,Q2Revenue,Q3Revenue,Q4Revenue,Q1Units,Q2Units,Q3Units,Q4Units
0,North,104045,199661,181373,86631,398,415,470,285
1,South,147888,93484,165294,122991,345,490,242,162
2,East,157455,132989,174019,54014,275,412,191,289
3,West,186672,86212,115726,61093,138,135,453,224
4,Central,143179,93525,191564,68070,269,272,421,249
5,Northeast,95714,113208,165668,85777,346,119,387,413
6,Northwest,152946,83828,56102,106958,125,420,314,157
7,Southeast,159616,199783,168015,132074,454,363,441,441
8,Southwest,155983,53420,76641,60729,405,499,150,404
9,Central-East,174123,146752,153746,155864,112,241,252,279

In [5]:
shape=df.shape
print(f"Shape:{shape}")

Shape:(10, 9)

In [13]:
data=df.values
print(f"DataTypes:{data}")

DataTypes:[['North' 104045 199661 181373 86631 398 415 470 285]
 ['South' 147888 93484 165294 122991 345 490 242 162]
 ['East' 157455 132989 174019 54014 275 412 191 289]
 ['West' 186672 86212 115726 61093 138 135 453 224]
 ['Central' 143179 93525 191564 68070 269 272 421 249]
 ['Northeast' 95714 113208 165668 85777 346 119 387 413]
 ['Northwest' 152946 83828 56102 106958 125 420 314 157]
 ['Southeast' 159616 199783 168015 132074 454 363 441 441]
 ['Southwest' 155983 53420 76641 60729 405 499 150 404]
 ['Central-East' 174123 146752 153746 155864 112 241 252 279]]

In [6]:
regional_performance=df[['RegionName','Q1Revenue','Q2Revenue','Q3Revenue','Q4Revenue']]
regional_performance

     RegionName  Q1Revenue  Q2Revenue  Q3Revenue  Q4Revenue
0         North     104045     199661     181373      86631
1         South     147888      93484     165294     122991
2          East     157455     132989     174019      54014
3          West     186672      86212     115726      61093
4       Central     143179      93525     191564      68070
5     Northeast      95714     113208     165668      85777
6     Northwest     152946      83828      56102     106958
7     Southeast     159616     199783     168015     132074
8     Southwest     155983      53420      76641      60729
9  Central-East     174123     146752     153746     155864

In [7]:
regional_shape=regional_performance.shape
print(f"Regional_performance shape:{regional_shape}")

Regional_performance shape:(10, 5)

In [8]:
regional_data=regional_performance.values
print(f"Regional_performance datatypes:{regional_data}")

Regional_performance datatypes:[['North' 104045 199661 181373 86631]
 ['South' 147888 93484 165294 122991]
 ['East' 157455 132989 174019 54014]
 ['West' 186672 86212 115726 61093]
 ['Central' 143179 93525 191564 68070]
 ['Northeast' 95714 113208 165668 85777]
 ['Northwest' 152946 83828 56102 106958]
 ['Southeast' 159616 199783 168015 132074]
 ['Southwest' 155983 53420 76641 60729]
 ['Central-East' 174123 146752 153746 155864]]

## Q2.2: Annual Revenue Calculation

#### Calculate the total annual revenue for each region (sum of Q1, Q2, Q3, Q4 revenues)

In [32]:
region=df[['Q1Revenue','Q2Revenue','Q3Revenue','Q4Revenue']]
region

   Q1Revenue  Q2Revenue  Q3Revenue  Q4Revenue
0     104045     199661     181373      86631
1     147888      93484     165294     122991
2     157455     132989     174019      54014
3     186672      86212     115726      61093
4     143179      93525     191564      68070
5      95714     113208     165668      85777
6     152946      83828      56102     106958
7     159616     199783     168015     132074
8     155983      53420      76641      60729
9     174123     146752     153746     155864

In [33]:
total_revenue=region.sum(axis=1)
total_revenue

0    571710
1    529657
2    518477
3    449703
4    496338
5    460367
6    399834
7    659488
8    346773
9    630485
dtype: int64

In [65]:
print("Annual Revenue per Region:")
for i, region in enumerate(df['RegionName']):
    print(f"{region}: ${total_revenue[i]:,.0f}")

Annual Revenue per Region:
North: $571,710
South: $529,657
East: $518,477
West: $449,703
Central: $496,338
Northeast: $460,367
Northwest: $399,834
Southeast: $659,488
Southwest: $346,773
Central-East: $630,485

## Q2.3: Quarterly Average

#### Find the average units sold per quarter across all regions

In [12]:
region_units=df[['Q1Units','Q2Units','Q3Units','Q4Units']]
region_units

   Q1Units  Q2Units  Q3Units  Q4Units
0      398      415      470      285
1      345      490      242      162
2      275      412      191      289
3      138      135      453      224
4      269      272      421      249
5      346      119      387      413
6      125      420      314      157
7      454      363      441      441
8      405      499      150      404
9      112      241      252      279

In [86]:
region_unit=df[['Q1Units','Q2Units','Q3Units','Q4Units']].values
region_unit

array([[398, 415, 470, 285],
       [345, 490, 242, 162],
       [275, 412, 191, 289],
       [138, 135, 453, 224],
       [269, 272, 421, 249],
       [346, 119, 387, 413],
       [125, 420, 314, 157],
       [454, 363, 441, 441],
       [405, 499, 150, 404],
       [112, 241, 252, 279]])

In [14]:
avg_units=region_units.mean(axis=1)
avg_units

0    392.00
1    309.75
2    291.75
3    237.50
4    302.75
5    316.25
6    254.00
7    424.75
8    364.50
9    221.00
dtype: float64

In [66]:
print("Average Units per Region:")
for i, region_units in enumerate(df['RegionName']):
    print(f"{region_units}: ${avg_units[i]:,.0f}")

Average Units per Region:
North: $392
South: $310
East: $292
West: $238
Central: $303
Northeast: $316
Northwest: $254
Southeast: $425
Southwest: $364
Central-East: $221

## Q2.4: Conditional Filtering

#### Identify regions where Q4 revenue is higher than the annual average revenue.

In [46]:
Filter_region=df[['Q1Revenue','Q2Revenue','Q3Revenue','Q4Revenue']].values
Filter_region

array([[104045, 199661, 181373,  86631],
       [147888,  93484, 165294, 122991],
       [157455, 132989, 174019,  54014],
       [186672,  86212, 115726,  61093],
       [143179,  93525, 191564,  68070],
       [ 95714, 113208, 165668,  85777],
       [152946,  83828,  56102, 106958],
       [159616, 199783, 168015, 132074],
       [155983,  53420,  76641,  60729],
       [174123, 146752, 153746, 155864]])

In [48]:
q4_revenue=Filter_region[:,3]
q4_revenue

array([ 86631, 122991,  54014,  61093,  68070,  85777, 106958, 132074,
        60729, 155864])

In [56]:
avg_revenue=total_revenue.mean()
print(f"Average Revenue:{avg_revenue}")

Average Revenue:506283.2

In [57]:
high_q4=q4_revenue>avg_revenue
print(f"High_Q4_Salary:{high_q4}")

High_Q4_Salary:[False False False False False False False False False False]

In [58]:
high_q4_regions= df.loc[high_q4, 'RegionName'].tolist()
print(f"High_Q4_Regions:{high_q4_regions}")

High_Q4_Regions:[]

## Q2.5: 2D Matrix Operations

#### Create a 2D matrix of quarterly revenues and compute column-wise totals (total revenue per quarter)

In [188]:
quarter=['Quarter_1','Quarter_2','Quarter_3','Quarter_4']

In [189]:
revenue_matrix=Filter_region
quarterly_revenue=revenue_matrix.sum(axis=0)
quarterly_revenue

array([1477621, 1202862, 1448148,  934201])

In [190]:
print("Total Revenue per Quarter")
for q, total in zip(quarter, quarterly_revenue):
    print(f"{q}:${total:,.0f}")

Total Revenue per Quarter
Quarter_1:$1,477,621
Quarter_2:$1,202,862
Quarter_3:$1,448,148
Quarter_4:$934,201

## Q2.6: Min-Max Normalization

#### Normalize all revenue values between 0 and 1 using min-max normalization.

In [73]:
revenue_flat=Filter_region.flatten()

In [75]:
normalized=(revenue_flat/revenue_flat.min())/(revenue_flat.max()-revenue_flat.min())
normalized

array([1.33071799e-05, 2.55363049e-05, 2.31973006e-05, 1.10799587e-05,
       1.89146256e-05, 1.19564458e-05, 2.11408236e-05, 1.57303413e-05,
       2.01382288e-05, 1.70090687e-05, 2.22567364e-05, 6.90829944e-06,
       2.38750338e-05, 1.10263693e-05, 1.48011601e-05, 7.81369159e-06,
       1.83123525e-05, 1.19616897e-05, 2.45007123e-05, 8.70603812e-06,
       1.22416591e-05, 1.44791121e-05, 2.11886576e-05, 1.09707335e-05,
       1.95615353e-05, 1.07214597e-05, 7.17535112e-06, 1.36797477e-05,
       2.04146170e-05, 2.55519085e-05, 2.14888349e-05, 1.68920417e-05,
       1.99499624e-05, 6.83232784e-06, 9.80225455e-06, 7.76713661e-06,
       2.22700378e-05, 1.87693331e-05, 1.96638539e-05, 1.99347425e-05])

In [76]:
print("Normalized (first 10):")
print(normalized[:10])
print(f"Min: {normalized.min()}, Max: {normalized.max()}")

Normalized (first 10):
[1.33071799e-05 2.55363049e-05 2.31973006e-05 1.10799587e-05
 1.89146256e-05 1.19564458e-05 2.11408236e-05 1.57303413e-05
 2.01382288e-05 1.70090687e-05]
Min: 6.8323278424191905e-06, Max: 2.5551908523811927e-05

## Q2.7: Boolean Masking

#### Use Boolean indexing to filter regions with total annual revenue > 500,000.

In [78]:
total_revenue

0    571710
1    529657
2    518477
3    449703
4    496338
5    460367
6    399834
7    659488
8    346773
9    630485
dtype: int64

In [116]:
high_revenue_mask =total_revenue>500000
high_revenue_mask

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7     True
8    False
9     True
dtype: bool

In [80]:
high_revenue_regions = df.loc[high_revenue_mask,['RegionName', 'Q1Revenue', 'Q2Revenue', 'Q3Revenue', 'Q4Revenue']]

In [81]:
print("Regions with revenue > $500,000:")
print(high_revenue_regions)

Regions with revenue > $500,000:
     RegionName  Q1Revenue  Q2Revenue  Q3Revenue  Q4Revenue
0         North     104045     199661     181373      86631
1         South     147888      93484     165294     122991
2          East     157455     132989     174019      54014
7     Southeast     159616     199783     168015     132074
9  Central-East     174123     146752     153746     155864

## Q2.8: Element-wise Division

#### Calculate the revenue per unit for each region and quarter (Revenue / Units).

In [194]:
quarter=['Quarter_1','Quarter_2','Quarter_3','Quarter_4']

In [195]:
revenue_per_unit=Filter_region/region_unit
revenue_per_unit

array([[ 261.41959799,  481.11084337,  385.9       ,  303.96842105],
       [ 428.66086957,  190.78367347,  683.03305785,  759.2037037 ],
       [ 572.56363636,  322.78883495,  911.09424084,  186.89965398],
       [1352.69565217,  638.60740741,  255.46578366,  272.73660714],
       [ 532.26394052,  343.84191176,  455.02137767,  273.37349398],
       [ 276.6300578 ,  951.32773109,  428.08268734,  207.69249395],
       [1223.568     ,  199.59047619,  178.66878981,  681.2611465 ],
       [ 351.57709251,  550.36639118,  380.98639456,  299.48752834],
       [ 385.14320988,  107.05410822,  510.94      ,  150.31930693],
       [1554.66964286,  608.92946058,  610.1031746 ,  558.65232975]])

In [196]:
print("Revenue per Unit for each regions:")
for i in range(len(revenue_per_unit)):
    print(f"\n{df.loc[i, 'RegionName']}:")
    for q, val in zip(quarter,revenue_per_unit[i]):
        print(f"{q}: ${val:,.2f}")

Revenue per Unit for each regions:

North:
Quarter_1: $261.42
Quarter_2: $481.11
Quarter_3: $385.90
Quarter_4: $303.97

South:
Quarter_1: $428.66
Quarter_2: $190.78
Quarter_3: $683.03
Quarter_4: $759.20

East:
Quarter_1: $572.56
Quarter_2: $322.79
Quarter_3: $911.09
Quarter_4: $186.90

West:
Quarter_1: $1,352.70
Quarter_2: $638.61
Quarter_3: $255.47
Quarter_4: $272.74

Central:
Quarter_1: $532.26
Quarter_2: $343.84
Quarter_3: $455.02
Quarter_4: $273.37

Northeast:
Quarter_1: $276.63
Quarter_2: $951.33
Quarter_3: $428.08
Quarter_4: $207.69

Northwest:
Quarter_1: $1,223.57
Quarter_2: $199.59
Quarter_3: $178.67
Quarter_4: $681.26

Southeast:
Quarter_1: $351.58
Quarter_2: $550.37
Quarter_3: $380.99
Quarter_4: $299.49

Southwest:
Quarter_1: $385.14
Quarter_2: $107.05
Quarter_3: $510.94
Quarter_4: $150.32

Central-East:
Quarter_1: $1,554.67
Quarter_2: $608.93
Quarter_3: $610.10
Quarter_4: $558.65

## Q2.9: Statistical Analysis

#### Calculate the standard deviation of revenue and identify outlier regions (> 2 std deviations from mean).

In [102]:
revenue_mean=revenue_flat.mean()
print(f"Revenue_Mean:{revenue_flat_mean:,.0f}")

Revenue_Mean:126,571

In [101]:
revenue_std=revenue_flat.std()
print(f"Revenue_Std:{revenue_flat_std:,.0f}")

Revenue_Std:44,268

In [107]:
outlier=np.abs(revenue_flat-revenue_mean)>2*revenue_std
outlier

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [108]:
num_outliers = outlier.sum()
print(f"Number of outlier values: {num_outliers}")

Number of outlier values: 0

## Q2.10: Correlation Matrix

#### Create a correlation matrix between quarterly revenues using NumPy.

In [119]:
corr_matrix = np.corrcoef(Filter_region)

In [120]:
print("Correlation Matrix (Quarterly Revenues):")
print("Quarters: Q1, Q2, Q3, Q4")
print(corr_matrix)

Correlation Matrix (Quarterly Revenues):
Quarters: Q1, Q2, Q3, Q4
[[ 1.         -0.19394258  0.568987   -0.14902988  0.35630856  0.71083041
  -0.73534366  0.88790412 -0.44293514 -0.66841005]
 [-0.19394258  1.          0.49651263  0.54293075  0.82526068  0.51396624
  -0.01564483 -0.39362621  0.51605916  0.51926089]
 [ 0.568987    0.49651263  1.          0.69371309  0.87760673  0.69046738
  -0.16155858  0.58277202  0.44293922  0.20611763]
 [-0.14902988  0.54293075  0.69371309  1.          0.59623947  0.04872818
   0.57703248  0.08556043  0.95155438  0.83509133]
 [ 0.35630856  0.82526068  0.87760673  0.59623947  1.          0.8118037
  -0.27435863  0.19264118  0.40199323  0.2526475 ]
 [ 0.71083041  0.51396624  0.69046738  0.04872818  0.8118037   1.
  -0.78176378  0.38868991 -0.20394056 -0.35633113]
 [-0.73534366 -0.01564483 -0.16155858  0.57703248 -0.27435863 -0.78176378
   1.         -0.35265721  0.76970373  0.84137343]
 [ 0.88790412 -0.39362621  0.58277202  0.08556043  0.19264118  0.38868991
  -0.35265721  1.         -0.17878271 -0.4310432 ]
 [-0.44293514  0.51605916  0.44293922  0.95155438  0.40199323 -0.20394056
   0.76970373 -0.17878271  1.          0.96200183]
 [-0.66841005  0.51926089  0.20611763  0.83509133  0.2526475  -0.35633113
   0.84137343 -0.4310432   0.96200183  1.        ]]

In [121]:
corr_matrix = np.corrcoef(Filter_region.T) # Transpose is used to fixed the matrix automatically by the dataframe
print(f"Correlation_Matrix:{corr_matrix}")

Correlation_Matrix:[[ 1.         -0.26172067 -0.3622283   0.12233413]
 [-0.26172067  1.          0.59392186  0.41592596]
 [-0.3622283   0.59392186  1.          0.08891746]
 [ 0.12233413  0.41592596  0.08891746  1.        ]]

## Challenge Extension

### Challenge 1

#### Create a 3D array structure and perform multi-axis operations.

In [162]:
arr = np.arange(1,37).reshape(3,3,4)    
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [168]:
# It is happened between the layers and rows
print(f"Sum of a 3D array:{np.sum(arr,axis=(0,1))}")
print(f"Minimum of a 3D array:{np.min(arr,axis=(0,1))}")
print(f"Maximum of a 3D array:{np.max(arr,axis=(0,1))}")
print(f"Mean of a 3D array:{np.mean(arr,axis=(0,1))}")
print(f"Standard Deviation of a 3D array:{np.std(arr,axis=(0,1))}")

Sum of a 3D array:[153 162 171 180]
Minimum of a 3D array:[1 2 3 4]
Maximum of a 3D array:[33 34 35 36]
Mean of a 3D array:[17. 18. 19. 20.]
Standard Deviation of a 3D array:[10.32795559 10.32795559 10.32795559 10.32795559]

In [169]:
# It is happened between the cols and rows
print(f"Sum of a 3D array:{np.sum(arr,axis=(1,2))}")
print(f"Minimum of a 3D array:{np.min(arr,axis=(1,2))}")
print(f"Maximum of a 3D array:{np.max(arr,axis=(1,2))}")
print(f"Mean of a 3D array:{np.mean(arr,axis=(1,2))}")
print(f"Standard Deviation of a 3D array:{np.std(arr,axis=(1,2))}")

Sum of a 3D array:[ 78 222 366]
Minimum of a 3D array:[ 1 13 25]
Maximum of a 3D array:[12 24 36]
Mean of a 3D array:[ 6.5 18.5 30.5]
Standard Deviation of a 3D array:[3.45205253 3.45205253 3.45205253]

In [170]:
# It is happened between the cols and layers
print(f"Sum of a 3D array:{np.sum(arr,axis=(1,0))}")
print(f"Minimum of a 3D array:{np.min(arr,axis=(1,0))}")
print(f"Maximum of a 3D array:{np.max(arr,axis=(1,0))}")
print(f"Mean of a 3D array:{np.mean(arr,axis=(1,0))}")
print(f"Standard Deviation of a 3D array:{np.std(arr,axis=(1,0))}")

Sum of a 3D array:[153 162 171 180]
Minimum of a 3D array:[1 2 3 4]
Maximum of a 3D array:[33 34 35 36]
Mean of a 3D array:[17. 18. 19. 20.]
Standard Deviation of a 3D array:[10.32795559 10.32795559 10.32795559 10.32795559]

## Challenge 2

#### Implement z-score normalization instead of min-max.

In [198]:
#1D array
data = np.array([10, 20, 30, 40, 50])
z_score = (data - np.mean(data)) / np.std(data)
print("Z-score Normalized Data:")
print(z_score)

Z-score Normalized Data:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [199]:
#2D array
data = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400]])
z_score = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
print("Z-score Normalized Data:")
print(z_score)

Z-score Normalized Data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

In [201]:
z_score = (data - np.mean(data)) / np.std(data)
z_score

array([[-1.64316767, -0.54772256,  0.54772256],
       [-1.09544512,  0.        ,  1.09544512],
       [-0.54772256,  0.54772256,  1.64316767]])

In [202]:
#3D array
z_score = (arr - np.mean(arr, axis=(0,1))) / np.std(arr, axis=(0,1))
print(z_score)

[[[-1.54919334 -1.54919334 -1.54919334 -1.54919334]
  [-1.161895   -1.161895   -1.161895   -1.161895  ]
  [-0.77459667 -0.77459667 -0.77459667 -0.77459667]]

 [[-0.38729833 -0.38729833 -0.38729833 -0.38729833]
  [ 0.          0.          0.          0.        ]
  [ 0.38729833  0.38729833  0.38729833  0.38729833]]

 [[ 0.77459667  0.77459667  0.77459667  0.77459667]
  [ 1.161895    1.161895    1.161895    1.161895  ]
  [ 1.54919334  1.54919334  1.54919334  1.54919334]]]

In [206]:
print("Mean:", np.mean(z_score, axis=(0,1)))
print("Std :", np.std(z_score, axis=(0,1)))

Mean: [0. 0. 0. 0.]
Std : [1. 1. 1. 1.]

## Challenge 3

#### Detect and analyze seasonal patterns in quarterly data.

In [208]:
quarterly_data = np.array([
    [120, 150, 200, 170],   # Year 1
    [130, 160, 210, 180],   # Year 2
    [125, 155, 205, 175],   # Year 3
    [135, 165, 215, 185]    # Year 4
])
quarterly_data

array([[120, 150, 200, 170],
       [130, 160, 210, 180],
       [125, 155, 205, 175],
       [135, 165, 215, 185]])

In [210]:
# Calculate average revenue per quarter
quarterly_mean = np.mean(quarterly_data, axis=0)
quarters=['Quarter_1','Quarter_2','Quarter_3','Quarter_4']
for q, val in zip(quarters, quarterly_mean):
    print(f"{q} Average Revenue: {val}")                 #  Quarter with highest average → peak season
                                                         #  Quarter with lowest average → weak season

Quarter_1 Average Revenue: 127.5
Quarter_2 Average Revenue: 157.5
Quarter_3 Average Revenue: 207.5
Quarter_4 Average Revenue: 177.5

In [213]:
# Seasonal Index Calculation
overall_mean = np.mean(quarterly_data)
seasonal_index = quarterly_mean / overall_mean
for q, idx in zip(quarters, seasonal_index):
    print(f"{q} Seasonal Index: {idx:.2f}")             # Index > 1 → above-average quarter
                                                        # Index < 1 → below-average quarter

Quarter_1 Seasonal Index: 0.76
Quarter_2 Seasonal Index: 0.94
Quarter_3 Seasonal Index: 1.24
Quarter_4 Seasonal Index: 1.06

In [218]:
# Standard Deviation
quarterly_std = np.std(quarterly_data,axis=0)
for q, sd in zip(quarters, quarterly_std):
    print(f"{q} Std Dev: {sd:.2f}")                    # Low std → consistent seasonal behaviour
                                                       # High std → unstable seasonality

Quarter_1 Std Dev: 5.59
Quarter_2 Std Dev: 5.59
Quarter_3 Std Dev: 5.59
Quarter_4 Std Dev: 5.59

In [224]:
# Detect seasonal variation using standard deviation per region
seasonal_variation = revenue_matrix.std(axis=1)

In [230]:
for i in range(len(seasonal_variation)):
    region_name = df.loc[i, 'RegionName']
    variation = seasonal_variation[i]

In [231]:
print(f"{region_name}: ${variation:,.2f}")
max_var_idx = seasonal_variation.argmax()
print(f"\nRegion with the highest seasonal variation: {df.loc[max_var_idx, 'RegionName']}")

Central-East: $10,106.36

Region with the highest seasonal variation: North

In [234]:
# Detect seasonal variation using standard deviation per region
seasonal_variation = revenue_matrix.std(axis=1)
print("Seasonal Variation (Standard Deviation) per Region:")
for i in range(len(seasonal_variation)):
    region_name = df.loc[i, 'RegionName']
    variation = seasonal_variation[i]
print(f"{region_name}: ${variation:,.2f}")
max_var_idx = seasonal_variation.argmax()
print(f"\nRegion with the highest seasonal variation: {df.loc[max_var_idx, 'RegionName']}")

Seasonal Variation (Standard Deviation) per Region:
Central-East: $10,106.36

Region with the highest seasonal variation: North