## ASSIGNMENT 4: Data Summarization & Grouping

## Q4.1: Basic GroupBy

In [2]:
import pandas as pd 
df=pd.read_csv('assignment4_sales_transactions(in).csv')
df

,TransactionID,Date,Region,Category,ProductName,Quantity,UnitPrice,CustomerType,Revenue
0,5001,9/24/2024,North,Accessories,Tablet,39,99,Retail,3861
1,5002,7/1/2024,Central,Accessories,Monitor,35,499,Wholesale,17465
2,5003,1/13/2024,North,Accessories,Tablet,3,99,Corporate,297
3,5004,10/5/2024,North,Electronics,Tablet,37,199,Wholesale,7363
4,5005,8/4/2024,East,Software,Laptop,44,799,Wholesale,35156
...,...,...,...,...,...,...,...,...,...
195,5196,1/23/2024,West,Software,Laptop,11,499,Wholesale,5489
196,5197,2/22/2024,Central,Accessories,Keyboard,41,499,Corporate,20459
197,5198,6/13/2024,East,Software,Tablet,3,99,Retail,297
198,5199,7/20/2024,East,Electronics,Phone,28,99,Wholesale,2772
199,5200,3/23/2024,North,Software,Laptop,29,799,Wholesale,23171

#### Group sales data by Region and calculate total revenue per region.

In [9]:
total_revenue=df.groupby('Region')['Revenue'].sum()
print("Total Revenue by Region:")
print(total_revenue.reset_index())

Total Revenue by Region:
    Region  Revenue
0  Central   686469
1     East   514120
2    North   674732
3    South   667313
4     West   497216

## Q4.2: Multi-column GroupBy

#### Group by both Region and Category, showing transaction count and total revenue for each combination.

In [16]:
region_category=df.groupby(['Region','Category']).agg({"TransactionID":"count","Revenue":"sum"})
region_category=region_category.rename(columns={'TransactionID': 'TransactionCount'})

In [18]:
print("Region Category by Transaction count and total Revenue:")
print(region_category.reset_index())

Region Category by Transaction count and total Revenue:
     Region     Category  TransactionCount  Revenue
0   Central  Accessories                16   238640
1   Central  Electronics                 8    75852
2   Central     Software                12   371977
3      East  Accessories                 8   122736
4      East  Electronics                17   206977
5      East     Software                18   184407
6     North  Accessories                20   379503
7     North  Electronics                11   125602
8     North     Software                11   169627
9     South  Accessories                 9   127423
10    South  Electronics                18   278286
11    South     Software                16   261604
12     West  Accessories                11   191794
13     West  Electronics                14   139127
14     West     Software                11   166295

## Q4.3: Average Quantity Analysis

#### Calculate the average quantity sold per region and sort in descending order.

In [21]:
avg_quantity=df.groupby('Region')['Quantity'].mean().sort_values(ascending=False)

In [23]:
print("Average Quantity per Region:")
print(avg_quantity.reset_index())

Average Quantity per Region:
    Region   Quantity
0  Central  28.638889
1    North  27.809524
2    South  27.604651
3     East  25.116279
4     West  21.777778

## Q4.4: Pivot Table Creation

#### Create a pivot table with Region as rows, Category as columns, and sum of Revenue as values.

In [28]:
pivot = pd.pivot_table(
df, 
values='Revenue', 
index='Region', 
columns='Category', 
aggfunc='sum'
)

In [29]:
print("Pivot Table: Region x Category Revenue:")
print(pivot)

Pivot Table: Region x Category Revenue:
Category  Accessories  Electronics  Software
Region
Central        238640        75852    371977
East           122736       206977    184407
North          379503       125602    169627
South          127423       278286    261604
West           191794       139127    166295

## Q4.5: Calculated Columns

#### Add a calculated column 'RevenuePerUnit' (Revenue / Quantity) for each transaction

In [34]:
df['RevenuePerUnit']=df['Revenue']/df['Quantity']

In [37]:
print("RevenuePerUnit for each Transaction")
print(df[['TransactionID','Revenue','Quantity','RevenuePerUnit']])

RevenuePerUnit for each Transaction
     TransactionID  Revenue  Quantity  RevenuePerUnit
0             5001     3861        39            99.0
1             5002    17465        35           499.0
2             5003      297         3            99.0
3             5004     7363        37           199.0
4             5005    35156        44           799.0
..             ...      ...       ...             ...
195           5196     5489        11           499.0
196           5197    20459        41           499.0
197           5198      297         3            99.0
198           5199     2772        28            99.0
199           5200    23171        29           799.0

[200 rows x 4 columns]

## Q4.6 Top Products
#### Find the top 3 products by total revenue and display their sales details

In [43]:
top_3_products=df.groupby('ProductName')['Revenue'].sum().nlargest(3)
print("Top 3 products for Total Revenue:")
top_3_products.reset_index()

Top 3 products for Total Revenue:

  ProductName  Revenue
0       Phone   734124
1    Keyboard   703230
2      Tablet   631866

In [47]:
print(f"Sales Details:")
for product in top_3_products.index:
    product_data = df[df['ProductName'] == product]
    print(f"\n{product}:")
    print(f"  Total Revenue: ${product_data['Revenue'].sum():,.0f}")
    print(f"  Transaction Count: {len(product_data)}")
    print(f"  Average Order Value: ${product_data['Revenue'].mean():,.0f}")

Sales Details:

Phone:
  Total Revenue: $734,124
  Transaction Count: 42
  Average Order Value: $17,479

Keyboard:
  Total Revenue: $703,230
  Transaction Count: 40
  Average Order Value: $17,581

Tablet:
  Total Revenue: $631,866
  Transaction Count: 42
  Average Order Value: $15,044

## Q4.7: Customer Type Analysis
#### Group by CustomerType and calculate total revenue, transaction count, and average order value

In [56]:
customer_summary = df.groupby('CustomerType').agg({
'Revenue': ['sum', 'count', 'mean'],
'Quantity': 'sum'
})

In [58]:
print("Performance by Customer Type:")
print(customer_summary.reset_index())

Performance by Customer Type:
  CustomerType  Revenue                     Quantity
                    sum count          mean      sum
0    Corporate   850832    62  13723.096774     1568
1       Retail   852872    63  13537.650794     1728
2    Wholesale  1336146    75  17815.280000     1954

## Q4.8: Composite Analysis
#### Identify which region-category combination has the highest average revenue per transaction

In [64]:
region_category = df.groupby(['Region', 'Category'])['Revenue'].mean()
region_category.reset_index()

     Region     Category       Revenue
0   Central  Accessories  14915.000000
1   Central  Electronics   9481.500000
2   Central     Software  30998.083333
3      East  Accessories  15342.000000
4      East  Electronics  12175.117647
5      East     Software  10244.833333
6     North  Accessories  18975.150000
7     North  Electronics  11418.363636
8     North     Software  15420.636364
9     South  Accessories  14158.111111
10    South  Electronics  15460.333333
11    South     Software  16350.250000
12     West  Accessories  17435.818182
13     West  Electronics   9937.642857
14     West     Software  15117.727273

In [66]:
highest_combination = region_category.idxmax()
highest_combination

('Central', 'Software')

In [67]:
highest_avg = region_category.max()
highest_avg

30998.083333333332

In [68]:
print(f"Best Region-Category Combination: {highest_combination}")
print(f"Average Revenue per Transaction: ${highest_avg:,.0f}")

Best Region-Category Combination: ('Central', 'Software')
Average Revenue per Transaction: $30,998

## Q4.9: Summary Report Export
#### Create a summary CSV showing region-wise performance metrics

In [69]:
region_summary=df.groupby('Region').agg({'Revenue':['sum','count','mean'],'Quantity':['sum','mean'],'TransactionID':'count'}).round(2)

In [70]:
region_summary.to_csv('region_summary_report.csv',index=False)

In [72]:
print("Region Summary Report metrics:")
region_summary.reset_index()

Region Summary Report metrics:

    Region Revenue                 Quantity        TransactionID
               sum count      mean      sum   mean         count
0  Central  686469    36  19068.58     1031  28.64            36
1     East  514120    43  11956.28     1080  25.12            43
2    North  674732    42  16065.05     1168  27.81            42
3    South  667313    43  15518.91     1187  27.60            43
4     West  497216    36  13811.56      784  21.78            36

## Q4.10: Quarterly Summary
#### Generate a quarterly revenue summary grouped by region (requires Date extraction)

In [73]:
df['Date'] = pd.to_datetime(df['Date'])
df['Quarter'] = df['Date'].dt.quarter
df['Month'] = df['Date'].dt.month

In [76]:
quarterly_summary = df.groupby(['Region', 'Quarter'])['Revenue'].sum()
print("Quarterly Revenue by Region:")
print(quarterly_summary.reset_index())

Quarterly Revenue by Region:
     Region  Quarter  Revenue
0   Central        1    77975
1   Central        2   122365
2   Central        3   333156
3   Central        4   152973
4      East        1   134255
5      East        2   124937
6      East        3   198266
7      East        4    56662
8     North        1   266986
9     North        2   131785
10    North        3   179681
11    North        4    96280
12    South        1   211096
13    South        2   166858
14    South        3   159425
15    South        4   129934
16     West        1    18867
17     West        2   272696
18     West        3   114295
19     West        4    91358

In [78]:
quarterly_summary.to_csv('quarterly_revenue_by_region.csv',index=False)

## Challenge Extension
### Challenge 1: 
#### Create a rolling 7-day revenue analysis.

In [84]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date']

125   2024-01-01
96    2024-01-01
168   2024-01-05
61    2024-01-05
189   2024-01-06
         ...
6     2024-12-26
95    2024-12-26
78    2024-12-29
167   2024-12-30
66    2024-12-30
Name: Date, Length: 200, dtype: datetime64[ns]

In [88]:
df = df.sort_values('Date')
df.tail(7)

,TransactionID,Date,Region,Category,ProductName,Quantity,UnitPrice,CustomerType,Revenue,RevenuePerUnit,Quarter,Month,Revenue_7Day_Rolling
193,5194,2024-12-23,Central,Software,Laptop,37,799,Corporate,29563,799.0,4,12,10635.71
133,5134,2024-12-23,Central,Software,Keyboard,48,799,Wholesale,38352,799.0,4,12,13331.00
6,5007,2024-12-26,Central,Accessories,Keyboard,30,99,Wholesale,2970,99.0,4,12,12760.29
95,5096,2024-12-26,South,Software,Keyboard,44,199,Corporate,8756,199.0,4,12,13369.57
78,5079,2024-12-29,Central,Software,Tablet,40,99,Corporate,3960,99.0,4,12,13878.71
167,5168,2024-12-30,West,Accessories,Tablet,3,1299,Corporate,3897,1299.0,4,12,13184.57
66,5067,2024-12-30,West,Electronics,Monitor,39,199,Retail,7761,199.0,4,12,13608.43

In [91]:
df['Revenue_7Day_Rolling'] = df['Revenue'].rolling(window=7).mean().round(2)
df['Revenue_7Day_Rolling'].reset_index().tail(7)

     index  Revenue_7Day_Rolling
193    193              10635.71
194    133              13331.00
195      6              13113.71
196     95              13369.57
197     78              13878.71
198    167              13184.57
199     66              13608.43

In [93]:
print(df[['Date', 'Revenue', 'Revenue_7Day_Rolling']].tail(7))

          Date  Revenue  Revenue_7Day_Rolling
193 2024-12-23    29563              10635.71
133 2024-12-23    38352              13331.00
6   2024-12-26     2970              13113.71
95  2024-12-26     8756              13369.57
78  2024-12-29     3960              13878.71
167 2024-12-30     3897              13184.57
66  2024-12-30     7761              13608.43

### Challenge 2: 
#### Calculate month-over-month growth rates by region.

In [99]:
df['Month']=df['Date'].dt.month
df['Month'].reset_index().head(20)

    index  Month
0     125      1
1      96      1
2     168      1
3      61      1
4     189      1
5      53      1
6     135      1
7      49      1
8     162      1
9     129      1
10      2      1
11    123      1
12     84      1
13     14      1
14    119      1
15    195      1
16     28      1
17    144      1
18     62      1
19    156      2

In [104]:
monthly_revenue=df.groupby(['Region','Month'])['Revenue'].sum().reset_index()
monthly_revenue

     Region  Month  Revenue
0   Central      2    33627
1   Central      3    44348
2   Central      5    91917
3   Central      6    30448
4   Central      7   208703
5   Central      8    26847
6   Central      9    97606
7   Central     10    23028
8   Central     11    26859
9   Central     12   103086
10     East      1    43472
11     East      2    23768
12     East      3    67015
13     East      4    13216
14     East      5    35406
15     East      6    76315
16     East      7    20483
17     East      8   147198
18     East      9    30585
19     East     10    14273
20     East     11     2376
21     East     12    40013
22    North      1   172886
23    North      2    37619
24    North      3    56481
25    North      4     2587
26    North      5    55768
27    North      6    73430
28    North      8    70743
29    North      9   108938
30    North     10     7363
31    North     11    77377
32    North     12    11540
33    South      1    48334
34    South      2    98553
35    South      3    64209
36    South      4    30038
37    South      5   108606
38    South      6    28214
39    South      7    70915
40    South      8    72530
41    South      9    15980
42    South     10    58577
43    South     11    22954
44    South     12    48403
45     West      1     9279
46     West      3     9588
47     West      4    50357
48     West      5    64488
49     West      6   157851
50     West      7    11691
51     West      8   102604
52     West     10    33294
53     West     11    24323
54     West     12    33741

In [110]:
monthly_revenue['MoM_growth_%']=monthly_revenue.groupby('Region')['Revenue'].pct_change()*100
monthly_revenue['MoM_growth_%'].head(10).reset_index()

   index  MoM_growth_%
0      0           NaN
1      1     31.882119
2      2    107.263011
3      3    -66.874463
4      4    585.440751
5      5    -87.136265
6      6    263.563899
7      7    -76.407188
8      8     16.636269
9      9    283.804311

### Challenge 3: 
#### Generate a comprehensive business intelligence report with multiple views

In [117]:
# Revenue by Region
region_summary = df.groupby('Region').agg(
    TotalRevenue=('Revenue', 'sum'),
    AvgRevenue=('Revenue', 'mean'),
    TransactionCount=('Revenue', 'count')
).round(2).reset_index()
print("Region_Summary:")
region_summary

Region_Summary:

    Region  TotalRevenue  AvgRevenue  TransactionCount
0  Central        686469    19068.58                36
1     East        514120    11956.28                43
2    North        674732    16065.05                42
3    South        667313    15518.91                43
4     West        497216    13811.56                36

In [118]:
# monthly revenue by trend
monthly_summary = (df.groupby('Month')['Revenue'].sum().reset_index())
print("Monthly_Summary:")
monthly_summary

Monthly_Summary:

    Month  Revenue
0       1   273971
1       2   193567
2       3   241641
3       4    96198
4       5   356185
5       6   366258
6       7   311792
7       8   419922
8       9   253109
9      10   136535
10     11   153889
11     12   236783

In [119]:
# Region-Month Pivot Table
region_month_pivot = pd.pivot_table(df,
    values='Revenue',
    index='Region',
    columns='Month',
    aggfunc='sum',)
print("Region_Month_Pivot_Table:")
region_month_pivot

Region_Month_Pivot_Table:

Month,1,2,3,4,5,6,7,8,9,10,11,12
Region,,,,,,,,,,,,
Central,NaN,33627.0,44348.0,NaN,91917.0,30448.0,208703.0,26847.0,97606.0,23028.0,26859.0,103086.0
East,43472.0,23768.0,67015.0,13216.0,35406.0,76315.0,20483.0,147198.0,30585.0,14273.0,2376.0,40013.0
North,172886.0,37619.0,56481.0,2587.0,55768.0,73430.0,NaN,70743.0,108938.0,7363.0,77377.0,11540.0
South,48334.0,98553.0,64209.0,30038.0,108606.0,28214.0,70915.0,72530.0,15980.0,58577.0,22954.0,48403.0
West,9279.0,NaN,9588.0,50357.0,64488.0,157851.0,11691.0,102604.0,NaN,33294.0,24323.0,33741.0

In [121]:
# Top performing Regions
top_regions = region_summary.sort_values(by='TotalRevenue',ascending=False)
print("Top_Performing_Regions:")
top_regions

Top_Performing_Regions:

    Region  TotalRevenue  AvgRevenue  TransactionCount
0  Central        686469    19068.58                36
2    North        674732    16065.05                42
3    South        667313    15518.91                43
1     East        514120    11956.28                43
4     West        497216    13811.56                36

In [123]:
with pd.ExcelWriter('business_intelligence_report.xlsx') as writer:
    region_summary.to_excel(writer, sheet_name='Region_Summary', index=False)
    monthly_summary.to_excel(writer, sheet_name='Monthly_Summary', index=False)
    region_month_pivot.to_excel(writer, sheet_name='Region_Month_Pivot_Table',index=False)