## Load and Inspect the Data

#### Read the CSV into a Pandas DataFrame and display the first 5 rows

In [2]:
import pandas as pd
df = pd.read_csv('sales_data_raw.csv')

In [3]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185

In [4]:
df.describe()

           OrderID    Quantity    UnitPrice   CustomerID    TotalAmount
count   515.000000  515.000000   515.000000   515.000000     515.000000
mean   1250.603883   12.106796   463.097087  5104.452427    5089.194175
std     143.913487   20.056201   466.886482    56.813498   11867.721283
min    1001.000000    1.000000    19.000000  5001.000000      19.000000
25%    1124.500000    5.000000    49.000000  5057.500000     418.000000
50%    1252.000000   10.000000   299.000000  5108.000000    1343.000000
75%    1374.500000   14.500000   899.000000  5153.500000    6589.000000
max    1500.000000  181.000000  1299.000000  5200.000000  187056.000000

In [5]:
df.head()

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196

### Display the number of missing values for each column.

In [6]:
print(df.isnull().sum())

OrderID           0
Date              0
Region           10
Product           0
Category          0
Quantity          0
UnitPrice         0
CustomerID        0
SalesRep         10
PaymentMethod     5
TotalAmount       0
dtype: int64

### 2. Missing Values

#### a) Fill missing Region and SalesRep values with the string "Unknown".

In [7]:
df['Region'].fillna("Unknown",inplace = True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_12676\634409159.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Region'].fillna("Unknown",inplace = True)

In [8]:
df['SalesRep'].fillna("Unknown",inplace = True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_12676\2389215205.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['SalesRep'].fillna("Unknown",inplace = True)

In [9]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185

In [11]:
print(df['Region'].isnull().sum())

0

#### b) For missing PaymentMethod, fill with the mode method.

In [12]:
df['PaymentMethod'].fillna(df['PaymentMethod'].mode()[0], inplace = True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_4068\798329032.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PaymentMethod'].fillna(df['PaymentMethod'].mode()[0], inplace = True)

In [13]:
print(df['PaymentMethod'].isnull().sum())

0

### 3. Duplicates

#### a) Count the number of duplicate rows in the dataset.

In [186]:
df[df["OrderID"].isin(df["OrderID"][df["OrderID"].duplicated()])].sort_values("OrderID")

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
131,1066,2024-04-15,North,Headphones,Electronics,12,599,5152,Eve,Net Banking,7188
332,1066,2024-04-15,North,Headphones,Electronics,12,599,5152,Eve,Net Banking,7188
416,1100,2024-05-08,Central,Mouse,Accessories,2,49,5127,Bob,UPI,98
499,1100,2024-05-08,Central,Mouse,Accessories,2,49,5127,Bob,UPI,98
73,1105,2024-06-11,East,Headphones,Accessories,4,299,5176,Alice,Net Banking,1196
101,1105,2024-06-11,East,Headphones,Accessories,4,299,5176,Alice,Net Banking,1196
199,1111,2024-05-14,North,Charger,Electronics,12,79,5128,Diana,Credit Card,948
173,1111,2024-05-14,North,Charger,Electronics,12,79,5128,Diana,Credit Card,948
275,1123,2024-08-01,South,Mouse,Electronics,12,1299,5147,Charlie,Cash,15588
82,1123,2024-08-01,South,Mouse,Electronics,12,1299,5147,Charlie,Cash,15588
18,1185,2024-06-13,North,Mouse,Electronics,5,1299,5032,Alice,UPI,6495
507,1185,2024-06-13,North,Mouse,Electronics,5,1299,5032,Alice,UPI,6495
406,1280,2024-06-09,North,Mouse,Accessories,3,599,5158,Bob,Credit Card,1797
102,1280,2024-06-09,North,Mouse,Accessories,3,599,5158,Bob,Credit Card,1797
182,1282,2024-03-15,Central,Keyboard,Electronics,14,1299,5162,Charlie,Credit Card,18186
22,1282,2024-03-15,Central,Keyboard,Electronics,14,1299,5162,Charlie,Credit Card,18186
494,1309,2024-01-22,West,Headphones,Accessories,13,1299,5194,Bob,Net Banking,16887
126,1309,2024-01-22,West,Headphones,Accessories,13,1299,5194,Bob,Net Banking,16887
245,1314,2024-12-30,Central,Mouse,Accessories,4,299,5076,Eve,Debit Card,1196
482,1314,2024-12-30,Central,Mouse,Accessories,4,299,5076,Eve,Debit Card,1196
458,1319,2024-08-13,North,Tablet,Electronics,13,79,5161,Charlie,Credit Card,1027
65,1319,2024-08-13,North,Tablet,Electronics,13,79,5161,Charlie,Credit Card,1027
281,1362,2024-10-06,Central,Laptop,Electronics,16,19,5153,Frank,Cash,304
471,1362,2024-10-06,Central,Laptop,Electronics,16,19,5153,Frank,Cash,304
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
490,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
404,1416,2024-04-17,Central,Mouse,Accessories,5,899,5124,Eve,Debit Card,4495
7,1416,2024-04-17,central,Mouse,Accessories,5,899,5124,Eve,Debit Card,4495
205,1425,2024-11-06,West,Tablet,Accessories,7,79,5061,Bob,Cash,553
361,1425,2024-11-06,West,Tablet,Accessories,7,79,5061,Bob,Cash,553

#### b) Drop complete duplicates and reset the DataFrame index.

In [155]:
df = df.drop_duplicates().reset_index(drop = True)

In [156]:
df[df["OrderID"].isin(df["OrderID"][df["OrderID"].duplicated()])].sort_values("OrderID")

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
277,1362,2024-10-06,Central,Laptop,Electronics,16,19,5153,Frank,Cash,304
463,1362,2024-10-06,Central,Laptop,Electronics,16,19,5153,Frank,Cash,304
7,1416,2024-04-17,central,Mouse,Accessories,5,899,5124,Eve,Debit Card,4495
398,1416,2024-04-17,Central,Mouse,Accessories,5,899,5124,Eve,Debit Card,4495

### 4. Text Cleaning and Standardization

#### a) Remove leading/trailing spaces and set the 'Product' names to proper case (e.g., "Phone").

In [187]:
df['Product'] = df['Product'].str.strip().str.title()

In [188]:
df['Product'].reset_index()

     index     Product
0        0       Phone
1        1       Phone
2        2      Laptop
3        3      Laptop
4        4    Keyboard
..     ...         ...
510    510  Headphones
511    511  Headphones
512    512      Tablet
513    513       Phone
514    514      Laptop

[515 rows x 2 columns]

#### b) Standardize 'Region' to title case (e.g., "North")

In [189]:
df['Region'] = df['Region'].str.title()

In [190]:
df['Region']

0        North
1      Central
2         West
3        North
4        North
        ...
510      North
511       East
512       East
513    Central
514      South
Name: Region, Length: 515, dtype: object

### 5. Outlier Identification & Treatment

#### a) Calculate mean and standard deviation of Quantity. Identify rows where Quantity is more than 3 std deviations above the mean.

In [191]:
quantity_mean = df['Quantity'].mean()

In [192]:
quantity_std = df['Quantity'].std()

In [193]:
print(quantity_mean)

12.106796116504855

In [194]:
print(quantity_std)

20.056201492665096

In [195]:
df['Outlier_mask'] = df['Quantity'] > (quantity_mean + (3 * quantity_std))
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,False
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,False
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,False
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,False
...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,False
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,False
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,False
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,False
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,False

In [196]:
df.sort_values(by='Outlier_mask')

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False
346,1222,2024-11-19,Unknown,Tablet,Accessories,8,299,5171,Eve,Credit Card,2392,False
345,1437,2024-04-01,West,Charger,Accessories,12,79,5187,Eve,Cash,948,False
344,1411,2024-02-23,Central,Tablet,Electronics,7,299,5028,Diana,Net Banking,2093,False
343,1143,2024-02-21,East,Keyboard,Accessories,1,19,5098,Frank,Cash,19,False
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1373,2024-06-24,West,Tablet,Accessories,181,79,5145,Alice,Net Banking,14299,True
395,1327,2024-01-04,Central,Tablet,Accessories,175,19,5058,Frank,Cash,3325,True
216,1249,2024-05-07,Central,Headphones,Accessories,173,899,5109,Diana,Credit Card,155527,True
84,1040,2024-08-31,West,Headphones,Accessories,165,49,5049,Eve,Credit Card,8085,True
462,1320,2024-10-03,East,Headphones,Accessories,162,79,5163,Charlie,Cash,12798,True

#### b) Replace these outlier Quantity values with the median Quantity for their 'Product' group

In [1]:
product_median=df.groupby('Monthly_Charges')['Contract'].transform('median')
product_median

NameError: name 'df' is not defined

In [201]:
df['Outliermask'] = df['Quantity'] > (quantity_mean + (3 * quantity_std))
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Outliermask
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,False,False
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,False,False
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,False,False
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,False,False
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,False,False
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,False,False
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,False,False
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,False,False
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,False,False

In [204]:
df.loc[df['Outliermask'],'Quantity'] = product_median[df['Outliermask']]

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14944\2037616265.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[11.5 11.5  9.5  9.5 10.   9.  11.5  9.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Outliermask'],'Quantity'] = product_median[df['Outliermask']]

In [205]:
 df.sort_values(by='Outlier_mask')

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Outliermask
0,1305,2024-07-13,North,Phone,Electronics,14.0,599,5060,Diana,Net Banking,8386,False,False
346,1222,2024-11-19,Unknown,Tablet,Accessories,8.0,299,5171,Eve,Credit Card,2392,False,False
345,1437,2024-04-01,West,Charger,Accessories,12.0,79,5187,Eve,Cash,948,False,False
344,1411,2024-02-23,Central,Tablet,Electronics,7.0,299,5028,Diana,Net Banking,2093,False,False
343,1143,2024-02-21,East,Keyboard,Accessories,1.0,19,5098,Frank,Cash,19,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1373,2024-06-24,West,Tablet,Accessories,9.5,79,5145,Alice,Net Banking,14299,True,True
395,1327,2024-01-04,Central,Tablet,Accessories,9.5,19,5058,Frank,Cash,3325,True,True
216,1249,2024-05-07,Central,Headphones,Accessories,11.5,899,5109,Diana,Credit Card,155527,True,True
84,1040,2024-08-31,West,Headphones,Accessories,11.5,49,5049,Eve,Credit Card,8085,True,True
462,1320,2024-10-03,East,Headphones,Accessories,11.5,79,5163,Charlie,Cash,12798,True,True

### 6. Feature Engineering

#### a) Extract the month and year from the Date column into new columns.

In [8]:
df['Date']=pd.to_datetime(df['Date'])

In [9]:
df['Month']=df['Date'].dt.month

In [10]:
df['Year']=df['Date'].dt.year

In [11]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Month,Year
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386,7,2024
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735,10,2024
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598,11,2024
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190,11,2024
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196,2,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596,6,2024
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093,9,2024
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735,8,2024
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147,10,2024
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185,5,2024

#### b) Flag orders larger than the 95th percentile of TotalAmount with a boolean 'HighValue' column.

In [215]:
df['HighValue']=df['TotalAmount']>df['TotalAmount'].quantile(0.95)

In [216]:
df.sort_values(by="HighValue")

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount,Outlier_mask,Outliermask,Month,Year,HighValue
0,1305,2024-07-13,North,Phone,Electronics,14.0,599,5060,Diana,Net Banking,8386,False,False,7,2024,False
347,1096,2024-12-10,West,Tablet,Accessories,17.0,899,5178,Frank,Debit Card,15283,False,False,12,2024,False
346,1222,2024-11-19,Unknown,Tablet,Accessories,8.0,299,5171,Eve,Credit Card,2392,False,False,11,2024,False
345,1437,2024-04-01,West,Charger,Accessories,12.0,79,5187,Eve,Cash,948,False,False,4,2024,False
344,1411,2024-02-23,Central,Tablet,Electronics,7.0,299,5028,Diana,Net Banking,2093,False,False,2,2024,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,1075,2024-12-16,East,Phone,Electronics,19.0,1299,5163,Unknown,UPI,24681,False,False,12,2024,True
170,1235,2024-07-19,East,Laptop,Electronics,16.0,1299,5055,Bob,Cash,20784,False,False,7,2024,True
286,1311,2024-06-06,South,Charger,Accessories,16.0,1299,5108,Eve,UPI,20784,False,False,6,2024,True
451,1014,2024-12-25,East,Laptop,Accessories,15.0,1299,5103,Alice,Debit Card,19485,False,False,12,2024,True
252,1372,2024-09-02,East,Charger,Electronics,19.0,1299,5142,Eve,Debit Card,24681,False,False,9,2024,True

## 7.Aggregations & Grouping

#### a) Compute total and average revenue per Region and Product combination.

In [50]:
total_average = df.groupby(['Region', 'Product']).agg({'TotalAmount':['sum', 'mean']}).reset_index()

In [54]:
total_average.rename(columns={'sum':'Total','mean':'Average'})

     Region         Product TotalAmount
                                  Total       Average
0   Central      Keyboard           152    152.000000
1   Central        Laptop          3294   1647.000000
2   Central         Charger       44778   4070.727273
3   Central      Headphones      217647  21764.700000
4   Central        Keyboard      117858   5124.260870
5   Central          Laptop       47034   3135.600000
6   Central           Mouse       28375   1576.388889
7   Central           Phone       43545   4354.500000
8   Central          Tablet      116059   6108.368421
9      East    Headphones          7192   7192.000000
10     East        Laptop           209    209.000000
11     East         Charger       51966   4724.181818
12     East      Headphones       56571   4714.250000
13     East        Keyboard       55763   3485.187500
14     East          Laptop       68049   5670.750000
15     East           Mouse       19269   1926.900000
16     East           Phone       96420   5671.764706
17     East          Tablet       31165   2397.307692
18    North    Headphones          4792   4792.000000
19    North         Charger      121229   5510.409091
20    North      Headphones       53409   3814.928571
21    North        Keyboard       49328   3523.428571
22    North          Laptop       43505   3346.538462
23    North           Mouse      255462  19650.923077
24    North           Phone      119319   5965.950000
25    North          Tablet       10261   1026.100000
26    South        Laptop          2093   2093.000000
27    South         Charger       67862   4524.133333
28    South      Headphones       51158   6394.750000
29    South        Keyboard       30960   3440.000000
30    South          Laptop       66380   3687.777778
31    South           Mouse       88132   5508.250000
32    South           Phone      102281   7305.785714
33    South          Tablet       94206   7246.615385
34  Unknown         Charger        5196   5196.000000
35  Unknown        Keyboard        4035   2017.500000
36  Unknown          Laptop        5622   2811.000000
37  Unknown           Mouse        9584   9584.000000
38  Unknown           Phone       18875   9437.500000
39  Unknown          Tablet        3691   1845.500000
40     West    Headphones         14289  14289.000000
41     West        Laptop            98     98.000000
42     West         Phone          5391   5391.000000
43     West         Charger       43321   4332.100000
44     West      Headphones       87450   5830.000000
45     West        Keyboard       36059   3004.916667
46     West          Laptop       36304   3300.363636
47     West           Mouse       41473   2764.866667
48     West           Phone       29631   3703.875000
49     West          Tablet       81822   4545.666667
50  central        Keyboard         882    882.000000
51  central          Laptop         228    228.000000
52  central           Mouse        5394   2697.000000
53     east          Laptop         294    294.000000
54     east           Phone         152    152.000000
55    north           Mouse        1198   1198.000000
56    south         Charger        1798   1798.000000
57     west          Laptop       22083  22083.000000
58     west          Tablet         342    342.000000

#### b) For each month, show the best-selling product by total quantity.

In [59]:
sales_per_month=df.groupby(['Year','Month','Product']).agg({'Quantity':'sum'})

In [60]:
sales_per_month.head(20)

                           Quantity
Year Month Product
2024 1       Headphones           8
           Charger               71
           Headphones            77
           Keyboard              14
           Laptop                 2
           Mouse                169
           Phone                 24
           Tablet               197
     2       Laptop              21
           Charger               50
           Headphones            74
           Keyboard              85
           Laptop                59
           Mouse                 72
           Phone                 19
           Tablet                41
     3     Charger               25
           Headphones             9
           Keyboard              63
           Laptop                49

In [64]:
best_selling_product = sales_per_month.loc[sales_per_month.groupby(['Year','Month'])['Quantity'].idxmax()]

In [65]:
best_selling_product

                       Quantity
Year Month Product
2024 1     Tablet           197
     2     Keyboard          85
     3     Keyboard          63
     4     Mouse            131
     5     Headphones       247
     6     Tablet           264
     7     Keyboard          87
     8     Tablet           284
     9     Phone            157
     10    Headphones       197
     11    Keyboard         195
     12    Tablet           103

## 8.Pivot and Reshape

#### a) Create a pivot table with Region as rows, Product as columns, and sum of TotalAmount as values.

In [66]:
pivot_table_example = pd.pivot_table(df, 
                                     values='TotalAmount', 
                                     index='Region', 
                                     columns='Product', 
                                     aggfunc='sum', 
                                     fill_value=0)

In [67]:
pivot_table_example

Product,Headphones,Keyboard,Laptop,Phone,Charger,Headphones,Keyboard,Laptop,Mouse,Phone,Tablet
Region,,,,,,,,,,,
Central,0,152,3294,0,44778,217647,117858,47034,28375,43545,116059
East,7192,0,209,0,51966,56571,55763,68049,19269,96420,31165
North,4792,0,0,0,121229,53409,49328,43505,255462,119319,10261
South,0,0,2093,0,67862,51158,30960,66380,88132,102281,94206
Unknown,0,0,0,0,5196,0,4035,5622,9584,18875,3691
West,14289,0,98,5391,43321,87450,36059,36304,41473,29631,81822
central,0,0,0,0,0,0,882,228,5394,0,0
east,0,0,0,0,0,0,0,294,0,152,0
north,0,0,0,0,0,0,0,0,1198,0,0
south,0,0,0,0,1798,0,0,0,0,0,0
west,0,0,0,0,0,0,0,22083,0,0,342

## 9.SalesRep Analytics

 #### a) Which SalesRep handled the highest revenue overall? Show their total revenue.

In [68]:
total_revenue=df.groupby('SalesRep')['TotalAmount'].sum()

In [31]:
total_revenue.head(20)

SalesRep
Alice      368308
Bob        317880
Charlie    516371
Diana      472319
Eve        406726
Frank      472463
Unknown     66868
Name: TotalAmount, dtype: int64

In [69]:
best_sales_rep=total_revenue.idxmax()

In [70]:
best_sales_rep

'Charlie'

In [38]:
(best_sales_rep,total_revenue[best_sales_rep].item())

('Charlie', 516371)

#### b) List the top 3 SalesReps by total orders handled each.

In [71]:
top_3_salesreps=df.groupby('SalesRep').agg({'OrderID':'count'})

In [49]:
top_3_salesreps.nlargest(3,'OrderID')

          OrderID
SalesRep
Charlie        94
Eve            93
Alice          83

#### 10.Export the Cleaned Data Save the fully cleaned and engineered DataFrame to sales_data_cleaned.csv.

In [5]:
df.to_csv('sales_data_cleaned.csv', index=False)

In [ ]:
#Monthly Revenue

In [15]:
df.groupby('Month')['TotalAmount'].sum().reset_index()

    Month  TotalAmount
0       1       308498
1       2       206849
2       3       130769
3       4       239279
4       5       325690
5       6       215081
6       7       173964
7       8       170102
8       9       296871
9      10       198791
10     11       108317
11     12       246724

In [7]:
df

,OrderID,Date,Region,Product,Category,Quantity,UnitPrice,CustomerID,SalesRep,PaymentMethod,TotalAmount
0,1305,2024-07-13,North,Phone,Electronics,14,599,5060,Diana,Net Banking,8386
1,1500,2024-10-06,Central,Phone,Electronics,15,49,5199,Bob,Credit Card,735
2,1442,2024-11-13,West,Laptop,Accessories,2,1299,5008,Charlie,Cash,2598
3,1154,2024-11-22,North,Laptop,Accessories,10,19,5198,Eve,UPI,190
4,1414,2024-02-22,North,Keyboard,Electronics,4,299,5063,Alice,Net Banking,1196
...,...,...,...,...,...,...,...,...,...,...,...
510,1072,2024-06-10,North,Headphones,Electronics,4,899,5158,Frank,Cash,3596
511,1107,2024-09-17,East,Headphones,Electronics,7,1299,5149,Bob,Cash,9093
512,1271,2024-08-20,East,Tablet,Accessories,15,49,5139,Eve,Credit Card,735
513,1436,2024-10-01,Central,Phone,Electronics,3,49,5053,Eve,Credit Card,147
514,1103,2024-05-18,South,Laptop,Accessories,15,79,5148,Diana,Credit Card,1185

In [ ]:
#Quarterly Revenue

In [16]:
df.groupby('Month')['TotalAmount'].sum().reset_index().head(3)

   Month  TotalAmount
0      1       308498
1      2       206849
2      3       130769

In [17]:
#Top 5 products based on Quantity,Revenue,UnitPrice

In [19]:
df.groupby('Product')['Quantity'].sum().nlargest(5).reset_index()

      Product  Quantity
0      Tablet      1254
1  Headphones      1115
2    Keyboard       845
3       Mouse       803
4       Phone       727

In [20]:
df.groupby('Product')['TotalAmount'].sum().nlargest(5).reset_index()

      Product  TotalAmount
0  Headphones       466235
1       Mouse       448887
2       Phone       410223
3      Tablet       337546
4     Charger       336150

In [22]:
df.groupby('Product')['UnitPrice'].sum().nlargest(5).reset_index()

   Product  UnitPrice
0    Phone      38998
1  Charger      36499
2    Mouse      36104
3   Tablet      33834
4   Laptop      31756