## Q1.1: Load and Inspect

#### Load the sales dataset and display its shape, column names, and first 5 rows.

In [8]:
import pandas as pd
df=pd.read_csv("assignment1_sales_data.csv")
df

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
4,105,Mouse,Accessories,East,866,572,954,650,19,3042
5,106,Webcam,Accessories,North,497,330,835,437,299,2099
6,107,Tablet,Accessories,West,970,289,324,971,49,2554
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356
9,110,Speaker,Accessories,West,306,476,737,572,49,2091
10,111,Headphones,Accessories,West,114,382,229,250,49,975
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374
14,115,Charger,Accessories,North,560,358,771,362,299,2051
15,116,Speaker,Electronics,West,790,458,809,863,19,2920
16,117,Phone,Electronics,East,674,809,515,243,199,2241
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309
18,119,Charger,Accessories,North,842,510,935,723,199,3010
19,120,Phone,Accessories,East,340,748,538,671,19,2297
20,121,Speaker,Accessories,North,663,417,302,980,599,2362
21,122,Laptop,Accessories,South,195,776,283,101,299,1355
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541
23,124,Charger,Accessories,South,833,918,500,403,199,2654
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024
27,128,Tablet,Electronics,North,848,926,936,136,899,2846
28,129,Mouse,Accessories,West,754,473,983,259,79,2469
29,130,Headphones,Accessories,West,270,771,709,108,19,1858
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976
31,132,Tablet,Accessories,North,135,571,610,198,19,1514
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565
33,134,Tablet,Accessories,East,259,791,243,915,199,2208
34,135,Mouse,Accessories,East,938,212,708,307,79,2165
35,136,Speaker,Electronics,South,798,929,300,230,79,2257
36,137,Monitor,Accessories,West,342,596,223,503,599,1664
37,138,Mouse,Electronics,North,185,541,286,251,899,1263
38,139,Phone,Accessories,East,895,663,425,153,599,2136
39,140,Headphones,Electronics,West,677,367,563,219,599,1826
40,141,Monitor,Electronics,West,781,609,448,772,599,2610
41,142,Phone,Accessories,South,656,906,870,727,599,3159
42,143,Webcam,Accessories,East,673,485,759,686,599,2603
43,144,Monitor,Electronics,East,745,486,863,724,299,2818
44,145,Webcam,Accessories,North,895,212,502,519,79,2128
45,146,Speaker,Accessories,East,127,712,445,521,599,1805
46,147,Phone,Accessories,North,719,724,610,203,1299,2256
47,148,Headphones,Electronics,East,655,180,246,951,79,2032
48,149,Mouse,Electronics,South,439,798,247,353,79,1837
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398

In [12]:
print("Shape:",df.shape)

Shape: (50, 10)

In [14]:
print("ColNames:",df.columns.tolist())

ColNames: ['ProductID', 'ProductName', 'Category', 'Region', 'Q1Sales', 'Q2Sales', 'Q3Sales', 'Q4Sales', 'UnitPrice', 'TotalSales']

In [5]:
df.describe()

,ProductID,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,125.50000,617.240000,566.720000,552.020000,535.380000,486.600000,2271.360000
std,14.57738,270.604279,212.717312,257.904625,267.455424,477.585594,472.779094
min,101.00000,104.000000,180.000000,101.000000,101.000000,19.000000,975.000000
25%,113.25000,366.250000,390.750000,306.250000,311.750000,79.000000,2036.750000
50%,125.50000,659.500000,563.000000,508.500000,520.000000,299.000000,2277.000000
75%,137.75000,846.500000,745.750000,780.000000,739.750000,599.000000,2550.750000
max,150.00000,999.000000,929.000000,983.000000,996.000000,1299.000000,3374.000000

In [6]:
df.head()

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
4,105,Mouse,Accessories,East,866,572,954,650,19,3042

## Q1.2: Regional Analysis

#### Count the total number of products in each region and display the results.

In [78]:
df.groupby('Region').agg({'ProductID':'count'})

        ProductID
Region
East           18
North          14
South           6
West           12

In [179]:
total=df.groupby('Region').size().reset_index()
print("Total number of Products per each Region:",total)

Total number of Products per each Region:   Region   0
0   East  18
1  North  14
2  South   6
3   West  12

## Q1.3: Filter and Export High Sales

#### Filter all products where TotalSales > 2000 and save to a new CSV file named high_sales_products.csv

In [27]:
high_sales=df[df['TotalSales']>2000]
high_sales

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
4,105,Mouse,Accessories,East,866,572,954,650,19,3042
5,106,Webcam,Accessories,North,497,330,835,437,299,2099
6,107,Tablet,Accessories,West,970,289,324,971,49,2554
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356
9,110,Speaker,Accessories,West,306,476,737,572,49,2091
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374
14,115,Charger,Accessories,North,560,358,771,362,299,2051
15,116,Speaker,Electronics,West,790,458,809,863,19,2920
16,117,Phone,Electronics,East,674,809,515,243,199,2241
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309
18,119,Charger,Accessories,North,842,510,935,723,199,3010
19,120,Phone,Accessories,East,340,748,538,671,19,2297
20,121,Speaker,Accessories,North,663,417,302,980,599,2362
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541
23,124,Charger,Accessories,South,833,918,500,403,199,2654
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024
27,128,Tablet,Electronics,North,848,926,936,136,899,2846
28,129,Mouse,Accessories,West,754,473,983,259,79,2469
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565
33,134,Tablet,Accessories,East,259,791,243,915,199,2208
34,135,Mouse,Accessories,East,938,212,708,307,79,2165
35,136,Speaker,Electronics,South,798,929,300,230,79,2257
38,139,Phone,Accessories,East,895,663,425,153,599,2136
40,141,Monitor,Electronics,West,781,609,448,772,599,2610
41,142,Phone,Accessories,South,656,906,870,727,599,3159
42,143,Webcam,Accessories,East,673,485,759,686,599,2603
43,144,Monitor,Electronics,East,745,486,863,724,299,2818
44,145,Webcam,Accessories,North,895,212,502,519,79,2128
46,147,Phone,Accessories,North,719,724,610,203,1299,2256
47,148,Headphones,Electronics,East,655,180,246,951,79,2032
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398

In [29]:
high_sales.to_csv('high_sales_products.csv',index=False)

In [180]:
high_sales.count().reset_index()

         index   0
0    ProductID  39
1  ProductName  39
2     Category  39
3       Region  39
4      Q1Sales  39
5      Q2Sales  39
6      Q3Sales  39
7      Q4Sales  39
8    UnitPrice  39
9   TotalSales  39

## Q1.4: CSV Module Reading

#### Read the CSV file using the csv module (standard library) and print all product names.

In [93]:
import csv
with open('assignment1_sales_data.csv','r')as f:
    reader = csv.DictReader(f)
    print("Product Names:")
    for row in reader:
        print(f"{row['ProductName']}")

Product Names:
Mouse
Headphones
Keyboard
Speaker
Mouse
Webcam
Tablet
Mouse
Keyboard
Speaker
Headphones
Keyboard
Keyboard
Tablet
Charger
Speaker
Phone
Keyboard
Charger
Phone
Speaker
Laptop
Webcam
Charger
Monitor
Laptop
Webcam
Tablet
Mouse
Headphones
Monitor
Tablet
Speaker
Tablet
Mouse
Speaker
Monitor
Mouse
Phone
Headphones
Monitor
Phone
Webcam
Monitor
Webcam
Speaker
Phone
Headphones
Mouse
Keyboard

## Q1.5: Find Best Performer

#### Find the product with the highest TotalSales and display its complete details.

In [178]:
Best=df['TotalSales'].idxmax()
df.loc[Best].reset_index()

          index           13
0     ProductID          114
1   ProductName       Tablet
2      Category  Accessories
3        Region         East
4       Q1Sales          991
5       Q2Sales          844
6       Q3Sales          829
7       Q4Sales          710
8     UnitPrice         1299
9    TotalSales         3374
10    Growth_Q2   -14.833502
11    Growth_Q3    -1.777251
12    Growth_Q4   -14.354644
13   Avg_Growth   -10.321799

## Q1.6: Category Filtering

#### Create a CSV file containing only Electronics products with their quarterly sales (Q1-Q4).

In [67]:
Electronics=df[df['Category']=='Electronics']
Electronics_cols=['ProductName','Category','Region','Q1Sales','Q2Sales','Q3Sales','Q4Sales','UnitPrice']
Electronics[Electronics_cols].to_csv('Electronics quarterly sales.csv',index=False)

In [184]:
Electronics.count().reset_index()

         index   0
0    ProductID  17
1  ProductName  17
2     Category  17
3       Region  17
4      Q1Sales  17
5      Q2Sales  17
6      Q3Sales  17
7      Q4Sales  17
8    UnitPrice  17
9   TotalSales  17

## Q1.7: Summary Statistics

#### Calculate the average UnitPrice per region and write results to avg_price_by_region.csv

In [185]:
avg_price=df.groupby('Region')['UnitPrice'].mean()
avg_price.reset_index()

  Region   UnitPrice
0   East  479.555556
1  North  563.285714
2  South  425.666667
3   West  438.166667

In [79]:
avg_price.to_csv('avg_price_by_region.csv',index=False)

## Q1.8: Data Quality Check

#### Identify missing values in the dataset (if any) and handle them appropriately.

In [186]:
df.isnull().sum().reset_index()

          index  0
0     ProductID  0
1   ProductName  0
2      Category  0
3        Region  0
4       Q1Sales  0
5       Q2Sales  0
6       Q3Sales  0
7       Q4Sales  0
8     UnitPrice  0
9    TotalSales  0
10    Growth_Q2  0
11    Growth_Q3  0
12    Growth_Q4  0
13   Avg_Growth  0

## Q1.9: Sorting and Export

#### Sort the dataset by TotalSales in descending order and save as sorted_sales.csv

In [85]:
sort_sales=df.sort_values(by='TotalSales',ascending=False)
sort_sales

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374
41,142,Phone,Accessories,South,656,906,870,727,599,3159
4,105,Mouse,Accessories,East,866,572,954,650,19,3042
18,119,Charger,Accessories,North,842,510,935,723,199,3010
15,116,Speaker,Electronics,West,790,458,809,863,19,2920
27,128,Tablet,Electronics,North,848,926,936,136,899,2846
43,144,Monitor,Electronics,East,745,486,863,724,299,2818
23,124,Charger,Accessories,South,833,918,500,403,199,2654
40,141,Monitor,Electronics,West,781,609,448,772,599,2610
42,143,Webcam,Accessories,East,673,485,759,686,599,2603
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560
6,107,Tablet,Accessories,West,970,289,324,971,49,2554
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
28,129,Mouse,Accessories,West,754,473,983,259,79,2469
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398
20,121,Speaker,Accessories,North,663,417,302,980,599,2362
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309
19,120,Phone,Accessories,East,340,748,538,671,19,2297
35,136,Speaker,Electronics,South,798,929,300,230,79,2257
46,147,Phone,Accessories,North,719,724,610,203,1299,2256
16,117,Phone,Electronics,East,674,809,515,243,199,2241
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209
33,134,Tablet,Accessories,East,259,791,243,915,199,2208
34,135,Mouse,Accessories,East,938,212,708,307,79,2165
38,139,Phone,Accessories,East,895,663,425,153,599,2136
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136
44,145,Webcam,Accessories,North,895,212,502,519,79,2128
5,106,Webcam,Accessories,North,497,330,835,437,299,2099
9,110,Speaker,Accessories,West,306,476,737,572,49,2091
14,115,Charger,Accessories,North,560,358,771,362,299,2051
47,148,Headphones,Electronics,East,655,180,246,951,79,2032
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976
29,130,Headphones,Accessories,West,270,771,709,108,19,1858
48,149,Mouse,Electronics,South,439,798,247,353,79,1837
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829
39,140,Headphones,Electronics,West,677,367,563,219,599,1826
45,146,Speaker,Accessories,East,127,712,445,521,599,1805
36,137,Monitor,Accessories,West,342,596,223,503,599,1664
31,132,Tablet,Accessories,North,135,571,610,198,19,1514
21,122,Laptop,Accessories,South,195,776,283,101,299,1355
37,138,Mouse,Electronics,North,185,541,286,251,899,1263
10,111,Headphones,Accessories,West,114,382,229,250,49,975

In [86]:
sort_sales.to_csv('sorted_sales.csv',index=False)

## Q1.10: Data Merging

#### Merge this dataset with a region-level summary and export as merged_analysis.csv

In [187]:
region_summary=df.groupby('Region').agg({'TotalSales':'sum','UnitPrice':'mean'})
region_summary.rename(columns={'TotalSales':'RegionTotalSales','UnitPrice':'RegionUnitPrice'}).reset_index()

  Region  RegionTotalSales  RegionUnitPrice
0   East             43117       479.555556
1  North             30892       563.285714
2  South             13238       425.666667
3   West             26321       438.166667

In [104]:
merged=df.merge(region_summary,on='Region',how='left')
merged

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice_x,TotalSales_x,TotalSales_y,UnitPrice_y
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209,43117,479.555556
1,102,Headphones,Electronics,North,104,739,741,919,599,2503,30892,563.285714
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829,30892,563.285714
3,104,Speaker,Electronics,North,602,447,665,739,79,2453,30892,563.285714
4,105,Mouse,Accessories,East,866,572,954,650,19,3042,43117,479.555556
5,106,Webcam,Accessories,North,497,330,835,437,299,2099,30892,563.285714
6,107,Tablet,Accessories,West,970,289,324,971,49,2554,26321,438.166667
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442,30892,563.285714
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356,26321,438.166667
9,110,Speaker,Accessories,West,306,476,737,572,49,2091,26321,438.166667
10,111,Headphones,Accessories,West,114,382,229,250,49,975,26321,438.166667
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355,43117,479.555556
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560,43117,479.555556
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374,43117,479.555556
14,115,Charger,Accessories,North,560,358,771,362,299,2051,30892,563.285714
15,116,Speaker,Electronics,West,790,458,809,863,19,2920,26321,438.166667
16,117,Phone,Electronics,East,674,809,515,243,199,2241,43117,479.555556
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309,43117,479.555556
18,119,Charger,Accessories,North,842,510,935,723,199,3010,30892,563.285714
19,120,Phone,Accessories,East,340,748,538,671,19,2297,43117,479.555556
20,121,Speaker,Accessories,North,663,417,302,980,599,2362,30892,563.285714
21,122,Laptop,Accessories,South,195,776,283,101,299,1355,13238,425.666667
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541,43117,479.555556
23,124,Charger,Accessories,South,833,918,500,403,199,2654,13238,425.666667
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136,30892,563.285714
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433,26321,438.166667
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024,43117,479.555556
27,128,Tablet,Electronics,North,848,926,936,136,899,2846,30892,563.285714
28,129,Mouse,Accessories,West,754,473,983,259,79,2469,26321,438.166667
29,130,Headphones,Accessories,West,270,771,709,108,19,1858,26321,438.166667
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976,13238,425.666667
31,132,Tablet,Accessories,North,135,571,610,198,19,1514,30892,563.285714
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565,26321,438.166667
33,134,Tablet,Accessories,East,259,791,243,915,199,2208,43117,479.555556
34,135,Mouse,Accessories,East,938,212,708,307,79,2165,43117,479.555556
35,136,Speaker,Electronics,South,798,929,300,230,79,2257,13238,425.666667
36,137,Monitor,Accessories,West,342,596,223,503,599,1664,26321,438.166667
37,138,Mouse,Electronics,North,185,541,286,251,899,1263,30892,563.285714
38,139,Phone,Accessories,East,895,663,425,153,599,2136,43117,479.555556
39,140,Headphones,Electronics,West,677,367,563,219,599,1826,26321,438.166667
40,141,Monitor,Electronics,West,781,609,448,772,599,2610,26321,438.166667
41,142,Phone,Accessories,South,656,906,870,727,599,3159,13238,425.666667
42,143,Webcam,Accessories,East,673,485,759,686,599,2603,43117,479.555556
43,144,Monitor,Electronics,East,745,486,863,724,299,2818,43117,479.555556
44,145,Webcam,Accessories,North,895,212,502,519,79,2128,30892,563.285714
45,146,Speaker,Accessories,East,127,712,445,521,599,1805,43117,479.555556
46,147,Phone,Accessories,North,719,724,610,203,1299,2256,30892,563.285714
47,148,Headphones,Electronics,East,655,180,246,951,79,2032,43117,479.555556
48,149,Mouse,Electronics,South,439,798,247,353,79,1837,13238,425.666667
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398,43117,479.555556

In [105]:
merged.to_csv('merged_analysis.csv',index=False)

## Challenge Extension

### Challenge 1:

#### Create a report showing top 5 products per region and export as a single CSV.

In [127]:
sort=df.sort_values(['Region','TotalSales'],ascending=[True,False])
sort

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374
4,105,Mouse,Accessories,East,866,572,954,650,19,3042
43,144,Monitor,Electronics,East,745,486,863,724,299,2818
42,143,Webcam,Accessories,East,673,485,759,686,599,2603
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309
19,120,Phone,Accessories,East,340,748,538,671,19,2297
16,117,Phone,Electronics,East,674,809,515,243,199,2241
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209
33,134,Tablet,Accessories,East,259,791,243,915,199,2208
34,135,Mouse,Accessories,East,938,212,708,307,79,2165
38,139,Phone,Accessories,East,895,663,425,153,599,2136
47,148,Headphones,Electronics,East,655,180,246,951,79,2032
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024
45,146,Speaker,Accessories,East,127,712,445,521,599,1805
18,119,Charger,Accessories,North,842,510,935,723,199,3010
27,128,Tablet,Electronics,North,848,926,936,136,899,2846
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442
20,121,Speaker,Accessories,North,663,417,302,980,599,2362
46,147,Phone,Accessories,North,719,724,610,203,1299,2256
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136
44,145,Webcam,Accessories,North,895,212,502,519,79,2128
5,106,Webcam,Accessories,North,497,330,835,437,299,2099
14,115,Charger,Accessories,North,560,358,771,362,299,2051
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829
31,132,Tablet,Accessories,North,135,571,610,198,19,1514
37,138,Mouse,Electronics,North,185,541,286,251,899,1263
41,142,Phone,Accessories,South,656,906,870,727,599,3159
23,124,Charger,Accessories,South,833,918,500,403,199,2654
35,136,Speaker,Electronics,South,798,929,300,230,79,2257
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976
48,149,Mouse,Electronics,South,439,798,247,353,79,1837
21,122,Laptop,Accessories,South,195,776,283,101,299,1355
15,116,Speaker,Electronics,West,790,458,809,863,19,2920
40,141,Monitor,Electronics,West,781,609,448,772,599,2610
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565
6,107,Tablet,Accessories,West,970,289,324,971,49,2554
28,129,Mouse,Accessories,West,754,473,983,259,79,2469
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356
9,110,Speaker,Accessories,West,306,476,737,572,49,2091
29,130,Headphones,Accessories,West,270,771,709,108,19,1858
39,140,Headphones,Electronics,West,677,367,563,219,599,1826
36,137,Monitor,Accessories,West,342,596,223,503,599,1664
10,111,Headphones,Accessories,West,114,382,229,250,49,975

In [133]:
top_5=sort.groupby('Region').head(5)
top_5

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374
4,105,Mouse,Accessories,East,866,572,954,650,19,3042
43,144,Monitor,Electronics,East,745,486,863,724,299,2818
42,143,Webcam,Accessories,East,673,485,759,686,599,2603
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560
18,119,Charger,Accessories,North,842,510,935,723,199,3010
27,128,Tablet,Electronics,North,848,926,936,136,899,2846
1,102,Headphones,Electronics,North,104,739,741,919,599,2503
3,104,Speaker,Electronics,North,602,447,665,739,79,2453
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442
41,142,Phone,Accessories,South,656,906,870,727,599,3159
23,124,Charger,Accessories,South,833,918,500,403,199,2654
35,136,Speaker,Electronics,South,798,929,300,230,79,2257
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976
48,149,Mouse,Electronics,South,439,798,247,353,79,1837
15,116,Speaker,Electronics,West,790,458,809,863,19,2920
40,141,Monitor,Electronics,West,781,609,448,772,599,2610
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565
6,107,Tablet,Accessories,West,970,289,324,971,49,2554
28,129,Mouse,Accessories,West,754,473,983,259,79,2469

In [134]:
top_5.to_csv('top_5_products per Region.csv',index=False)

## Challenge 2

#### Calculate quarterly growth rate for each product and identify fastest-growing products

In [141]:
df['Growth_Q2']=(df['Q2Sales']-df['Q1Sales'])/df['Q1Sales']*100

In [142]:
df['Growth_Q3']=(df['Q3Sales']-df['Q2Sales'])/df['Q2Sales']*100

In [143]:
df['Growth_Q4']=(df['Q4Sales']-df['Q3Sales'])/df['Q3Sales']*100

In [150]:
df['Avg_Growth']=df[['Growth_Q2','Growth_Q3','Growth_Q4']].mean(axis=1)
df

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales,Growth_Q2,Growth_Q3,Growth_Q4,Avg_Growth
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209,-50.460829,-76.511628,701.980198,191.669247
1,102,Headphones,Electronics,North,104,739,741,919,599,2503,610.576923,0.270636,24.021592,211.623051
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829,90.851735,-47.272727,84.326019,42.635009
3,104,Speaker,Electronics,North,602,447,665,739,79,2453,-25.747508,48.769575,11.127820,11.383295
4,105,Mouse,Accessories,East,866,572,954,650,19,3042,-33.949192,66.783217,-31.865828,0.322732
5,106,Webcam,Accessories,North,497,330,835,437,299,2099,-33.601610,153.030303,-47.664671,23.921341
6,107,Tablet,Accessories,West,970,289,324,971,49,2554,-70.206186,12.110727,199.691358,47.198633
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442,-63.758389,49.382716,52.892562,12.838963
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356,-1.626016,3.719008,74.900398,25.664463
9,110,Speaker,Accessories,West,306,476,737,572,49,2091,55.555556,54.831933,-22.388060,29.333143
10,111,Headphones,Accessories,West,114,382,229,250,49,975,235.087719,-40.052356,9.170306,68.068556
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355,-23.510972,-79.234973,238.157895,45.137317
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560,11.332312,7.702889,-49.297573,-10.087457
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374,-14.833502,-1.777251,-14.354644,-10.321799
14,115,Charger,Accessories,North,560,358,771,362,299,2051,-36.071429,115.363128,-53.047990,8.747903
15,116,Speaker,Electronics,West,790,458,809,863,19,2920,-42.025316,76.637555,6.674907,13.762382
16,117,Phone,Electronics,East,674,809,515,243,199,2241,20.029674,-36.341162,-52.815534,-23.042341
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309,-42.367601,-37.657658,28.612717,-17.137514
18,119,Charger,Accessories,North,842,510,935,723,199,3010,-39.429929,83.333333,-22.673797,7.076536
19,120,Phone,Accessories,East,340,748,538,671,19,2297,120.000000,-28.074866,24.721190,38.882108
20,121,Speaker,Accessories,North,663,417,302,980,599,2362,-37.104072,-27.577938,224.503311,53.273767
21,122,Laptop,Accessories,South,195,776,283,101,299,1355,297.948718,-63.530928,-64.310954,56.702279
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541,-67.567568,-31.481481,348.648649,83.199867
23,124,Charger,Accessories,South,833,918,500,403,199,2654,10.204082,-45.533769,-19.400000,-18.243229
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136,-42.979452,160.060060,-59.237875,19.280911
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433,54.743083,-49.808429,91.094148,32.009600
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024,131.212121,-50.327654,45.646438,42.176968
27,128,Tablet,Electronics,North,848,926,936,136,899,2846,9.198113,1.079914,-85.470085,-25.064020
28,129,Mouse,Accessories,West,754,473,983,259,79,2469,-37.267905,107.822410,-73.652085,-1.032527
29,130,Headphones,Accessories,West,270,771,709,108,19,1858,185.555556,-8.041505,-84.767278,30.915591
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976,10.468750,-57.991513,11.784512,-11.912751
31,132,Tablet,Accessories,North,135,571,610,198,19,1514,322.962963,6.830123,-67.540984,87.417367
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565,-46.794872,156.325301,-10.928320,32.867370
33,134,Tablet,Accessories,East,259,791,243,915,199,2208,205.405405,-69.279393,276.543210,137.556407
34,135,Mouse,Accessories,East,938,212,708,307,79,2165,-77.398721,233.962264,-56.638418,33.308375
35,136,Speaker,Electronics,South,798,929,300,230,79,2257,16.416040,-67.707212,-23.333333,-24.874835
36,137,Monitor,Accessories,West,342,596,223,503,599,1664,74.269006,-62.583893,125.560538,45.748550
37,138,Mouse,Electronics,North,185,541,286,251,899,1263,192.432432,-47.134935,-12.237762,44.353245
38,139,Phone,Accessories,East,895,663,425,153,599,2136,-25.921788,-35.897436,-64.000000,-41.939741
39,140,Headphones,Electronics,West,677,367,563,219,599,1826,-45.790251,53.405995,-61.101243,-17.828500
40,141,Monitor,Electronics,West,781,609,448,772,599,2610,-22.023047,-26.436782,72.321429,7.953867
41,142,Phone,Accessories,South,656,906,870,727,599,3159,38.109756,-3.973510,-16.436782,5.899822
42,143,Webcam,Accessories,East,673,485,759,686,599,2603,-27.934621,56.494845,-9.617918,6.314102
43,144,Monitor,Electronics,East,745,486,863,724,299,2818,-34.765101,77.572016,-16.106605,8.900104
44,145,Webcam,Accessories,North,895,212,502,519,79,2128,-76.312849,136.792453,3.386454,21.288686
45,146,Speaker,Accessories,East,127,712,445,521,599,1805,460.629921,-37.500000,17.078652,146.736191
46,147,Phone,Accessories,North,719,724,610,203,1299,2256,0.695410,-15.745856,-66.721311,-27.257253
47,148,Headphones,Electronics,East,655,180,246,951,79,2032,-72.519084,36.666667,286.585366,83.577650
48,149,Mouse,Electronics,South,439,798,247,353,79,1837,81.776765,-69.047619,42.914980,18.548042
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398,-76.365663,354.245283,-66.147456,70.577388

In [172]:
Fastest=df.sort_values(by='Avg_Growth',ascending=False)
Fastest

,ProductID,ProductName,Category,Region,Q1Sales,Q2Sales,Q3Sales,Q4Sales,UnitPrice,TotalSales,Growth_Q2,Growth_Q3,Growth_Q4,Avg_Growth
1,102,Headphones,Electronics,North,104,739,741,919,599,2503,610.576923,0.270636,24.021592,211.623051
0,101,Mouse,Electronics,East,868,430,101,810,1299,2209,-50.460829,-76.511628,701.980198,191.669247
45,146,Speaker,Accessories,East,127,712,445,521,599,1805,460.629921,-37.500000,17.078652,146.736191
33,134,Tablet,Accessories,East,259,791,243,915,199,2208,205.405405,-69.279393,276.543210,137.556407
31,132,Tablet,Accessories,North,135,571,610,198,19,1514,322.962963,6.830123,-67.540984,87.417367
47,148,Headphones,Electronics,East,655,180,246,951,79,2032,-72.519084,36.666667,286.585366,83.577650
22,123,Webcam,Accessories,East,999,324,222,996,1299,2541,-67.567568,-31.481481,348.648649,83.199867
49,150,Keyboard,Electronics,East,897,212,963,326,49,2398,-76.365663,354.245283,-66.147456,70.577388
10,111,Headphones,Accessories,West,114,382,229,250,49,975,235.087719,-40.052356,9.170306,68.068556
21,122,Laptop,Accessories,South,195,776,283,101,299,1355,297.948718,-63.530928,-64.310954,56.702279
20,121,Speaker,Accessories,North,663,417,302,980,599,2362,-37.104072,-27.577938,224.503311,53.273767
6,107,Tablet,Accessories,West,970,289,324,971,49,2554,-70.206186,12.110727,199.691358,47.198633
36,137,Monitor,Accessories,West,342,596,223,503,599,1664,74.269006,-62.583893,125.560538,45.748550
11,112,Keyboard,Accessories,East,957,732,152,514,599,2355,-23.510972,-79.234973,238.157895,45.137317
37,138,Mouse,Electronics,North,185,541,286,251,899,1263,192.432432,-47.134935,-12.237762,44.353245
2,103,Keyboard,Accessories,North,317,605,319,588,19,1829,90.851735,-47.272727,84.326019,42.635009
26,127,Webcam,Accessories,East,330,763,379,552,1299,2024,131.212121,-50.327654,45.646438,42.176968
19,120,Phone,Accessories,East,340,748,538,671,19,2297,120.000000,-28.074866,24.721190,38.882108
34,135,Mouse,Accessories,East,938,212,708,307,79,2165,-77.398721,233.962264,-56.638418,33.308375
32,133,Speaker,Electronics,West,624,332,851,758,1299,2565,-46.794872,156.325301,-10.928320,32.867370
25,126,Laptop,Electronics,West,506,783,393,751,1299,2433,54.743083,-49.808429,91.094148,32.009600
29,130,Headphones,Accessories,West,270,771,709,108,19,1858,185.555556,-8.041505,-84.767278,30.915591
9,110,Speaker,Accessories,West,306,476,737,572,49,2091,55.555556,54.831933,-22.388060,29.333143
8,109,Keyboard,Accessories,West,492,484,502,878,599,2356,-1.626016,3.719008,74.900398,25.664463
5,106,Webcam,Accessories,North,497,330,835,437,299,2099,-33.601610,153.030303,-47.664671,23.921341
44,145,Webcam,Accessories,North,895,212,502,519,79,2128,-76.312849,136.792453,3.386454,21.288686
24,125,Monitor,Accessories,North,584,333,866,353,1299,2136,-42.979452,160.060060,-59.237875,19.280911
48,149,Mouse,Electronics,South,439,798,247,353,79,1837,81.776765,-69.047619,42.914980,18.548042
15,116,Speaker,Electronics,West,790,458,809,863,19,2920,-42.025316,76.637555,6.674907,13.762382
7,108,Mouse,Accessories,North,894,324,484,740,1299,2442,-63.758389,49.382716,52.892562,12.838963
3,104,Speaker,Electronics,North,602,447,665,739,79,2453,-25.747508,48.769575,11.127820,11.383295
43,144,Monitor,Electronics,East,745,486,863,724,299,2818,-34.765101,77.572016,-16.106605,8.900104
14,115,Charger,Accessories,North,560,358,771,362,299,2051,-36.071429,115.363128,-53.047990,8.747903
40,141,Monitor,Electronics,West,781,609,448,772,599,2610,-22.023047,-26.436782,72.321429,7.953867
18,119,Charger,Accessories,North,842,510,935,723,199,3010,-39.429929,83.333333,-22.673797,7.076536
42,143,Webcam,Accessories,East,673,485,759,686,599,2603,-27.934621,56.494845,-9.617918,6.314102
41,142,Phone,Accessories,South,656,906,870,727,599,3159,38.109756,-3.973510,-16.436782,5.899822
4,105,Mouse,Accessories,East,866,572,954,650,19,3042,-33.949192,66.783217,-31.865828,0.322732
28,129,Mouse,Accessories,West,754,473,983,259,79,2469,-37.267905,107.822410,-73.652085,-1.032527
12,113,Keyboard,Accessories,East,653,727,783,397,79,2560,11.332312,7.702889,-49.297573,-10.087457
13,114,Tablet,Accessories,East,991,844,829,710,1299,3374,-14.833502,-1.777251,-14.354644,-10.321799
30,131,Monitor,Electronics,South,640,707,297,332,1299,1976,10.468750,-57.991513,11.784512,-11.912751
17,118,Keyboard,Accessories,East,963,555,346,445,19,2309,-42.367601,-37.657658,28.612717,-17.137514
39,140,Headphones,Electronics,West,677,367,563,219,599,1826,-45.790251,53.405995,-61.101243,-17.828500
23,124,Charger,Accessories,South,833,918,500,403,199,2654,10.204082,-45.533769,-19.400000,-18.243229
16,117,Phone,Electronics,East,674,809,515,243,199,2241,20.029674,-36.341162,-52.815534,-23.042341
35,136,Speaker,Electronics,South,798,929,300,230,79,2257,16.416040,-67.707212,-23.333333,-24.874835
27,128,Tablet,Electronics,North,848,926,936,136,899,2846,9.198113,1.079914,-85.470085,-25.064020
46,147,Phone,Accessories,North,719,724,610,203,1299,2256,0.695410,-15.745856,-66.721311,-27.257253
38,139,Phone,Accessories,East,895,663,425,153,599,2136,-25.921788,-35.897436,-64.000000,-41.939741

## Challenge 3:
#### Detect and handle duplicate rows intelligently.

In [188]:
df[df.duplicated()].sum().reset_index()

          index    0
0     ProductID    0
1   ProductName    0
2      Category    0
3        Region    0
4       Q1Sales    0
5       Q2Sales    0
6       Q3Sales    0
7       Q4Sales    0
8     UnitPrice    0
9    TotalSales    0
10    Growth_Q2  0.0
11    Growth_Q3  0.0
12    Growth_Q4  0.0
13   Avg_Growth  0.0