## ASSIGNMENT 3: Introduction to Pandas

### Q3.1: Data Exploration

#### Load the student scores dataset and display its shape, info, and basic statistics

In [1]:
import pandas as pd
df=pd.read_csv('assignment3_student_scores(in).csv')
df

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage
0,1001,Student_1,92.0,4.0,16.0,16.0,F,79
1,1002,Student_2,71.0,40.0,23.0,29.0,A,83
2,1003,Student_3,82.0,72.0,97.0,5.0,B,71
3,1004,Student_4,NaN,33.0,10.0,36.0,B,94
4,1005,Student_5,99.0,NaN,15.0,45.0,A,92
5,1006,Student_6,2.0,61.0,58.0,98.0,B,92
6,1007,Student_7,NaN,98.0,92.0,62.0,A,96
7,1008,Student_8,29.0,85.0,58.0,31.0,F,71
8,1009,Student_9,63.0,64.0,89.0,66.0,F,62
9,1010,Student_10,32.0,46.0,18.0,24.0,A,60
10,1011,Student_11,21.0,0.0,70.0,53.0,F,92
11,1012,Student_12,NaN,13.0,32.0,45.0,F,99
12,1013,Student_13,NaN,8.0,38.0,NaN,F,69
13,1014,Student_14,41.0,89.0,0.0,85.0,C,88
14,1015,Student_15,NaN,NaN,56.0,26.0,D,72
15,1016,Student_16,14.0,62.0,22.0,89.0,B,71
16,1017,Student_17,46.0,51.0,41.0,32.0,C,90
17,1018,Student_18,54.0,3.0,15.0,47.0,F,61
18,1019,Student_19,2.0,22.0,59.0,41.0,A,94
19,1020,Student_20,6.0,14.0,0.0,98.0,F,82
20,1021,Student_21,38.0,35.0,NaN,23.0,D,76
21,1022,Student_22,NaN,70.0,36.0,6.0,F,85
22,1023,Student_23,13.0,85.0,8.0,44.0,A,67
23,1024,Student_24,8.0,41.0,18.0,7.0,D,88
24,1025,Student_25,NaN,56.0,2.0,15.0,F,85
25,1026,Student_26,91.0,27.0,53.0,NaN,D,69
26,1027,Student_27,70.0,43.0,23.0,14.0,B,85
27,1028,Student_28,7.0,61.0,71.0,65.0,B,93
28,1029,Student_29,NaN,91.0,83.0,62.0,F,66
29,1030,Student_30,35.0,61.0,88.0,NaN,D,63
30,1031,Student_31,3.0,26.0,92.0,62.0,A,70
31,1032,Student_32,5.0,76.0,81.0,21.0,F,88
32,1033,Student_33,3.0,69.0,34.0,85.0,B,95
33,1034,Student_34,62.0,8.0,40.0,41.0,B,84
34,1035,Student_35,43.0,96.0,67.0,53.0,F,80
35,1036,Student_36,61.0,43.0,20.0,96.0,D,95
36,1037,Student_37,94.0,58.0,7.0,59.0,B,69
37,1038,Student_38,71.0,95.0,16.0,4.0,D,96
38,1039,Student_39,61.0,51.0,47.0,5.0,B,68
39,1040,Student_40,79.0,57.0,NaN,NaN,B,83
40,1041,Student_41,52.0,38.0,21.0,46.0,C,94
41,1042,Student_42,88.0,55.0,37.0,39.0,B,94
42,1043,Student_43,40.0,NaN,50.0,12.0,A,95
43,1044,Student_44,44.0,1.0,26.0,29.0,F,77
44,1045,Student_45,NaN,86.0,20.0,NaN,F,98
45,1046,Student_46,87.0,96.0,27.0,18.0,D,91
46,1047,Student_47,7.0,1.0,96.0,54.0,B,83
47,1048,Student_48,NaN,89.0,60.0,89.0,A,82
48,1049,Student_49,80.0,31.0,3.0,22.0,D,91
49,1050,Student_50,34.0,54.0,NaN,11.0,C,96

In [2]:
shape=df.shape
print(f"Shape:{shape}")

Shape:(50, 8)

In [3]:
print("\n--- Dataset Info ---")
df.info()

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             50 non-null     int64
 1   Name                  50 non-null     object
 2   Math                  40 non-null     float64
 3   Science               47 non-null     float64
 4   English               47 non-null     float64
 5   History               45 non-null     float64
 6   Grade                 50 non-null     object
 7   AttendancePercentage  50 non-null     int64
dtypes: float64(4), int64(2), object(2)
memory usage: 3.3+ KB

In [4]:
print("\n--- Basic Statistics ---")
df.describe()

--- Basic Statistics ---

,StudentID,Math,Science,English,History,AttendancePercentage
count,50.00000,40.000000,47.000000,47.000000,45.000000,50.000000
mean,1025.50000,45.750000,50.319149,41.170213,42.444444,82.480000
std,14.57738,31.264586,29.805242,29.300036,27.820492,11.556851
min,1001.00000,2.000000,0.000000,0.000000,4.000000,60.000000
25%,1013.25000,13.750000,29.000000,18.000000,21.000000,71.000000
50%,1025.50000,43.500000,54.000000,36.000000,41.000000,84.500000
75%,1037.75000,71.000000,71.000000,59.500000,62.000000,92.750000
max,1050.00000,99.000000,98.000000,97.000000,98.000000,99.000000

## Q3.2: Average Score Calculation

#### Calculate the average score across all subjects (Math, Science, English, History) for each student

In [5]:
subjects=df[['Math','Science','English','History']]
df['Avg_score']=subjects.mean(axis=1)
print("\n---Average_score for each Student---")
df['Avg_score'].head(10)

---Average_score for each Student---

0    32.000000
1    40.750000
2    64.000000
3    26.333333
4    53.000000
5    54.750000
6    84.000000
7    50.750000
8    70.500000
9    30.000000
Name: Avg_score, dtype: float64

In [6]:
df

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score
0,1001,Student_1,92.0,4.0,16.0,16.0,F,79,32.000000
1,1002,Student_2,71.0,40.0,23.0,29.0,A,83,40.750000
2,1003,Student_3,82.0,72.0,97.0,5.0,B,71,64.000000
3,1004,Student_4,NaN,33.0,10.0,36.0,B,94,26.333333
4,1005,Student_5,99.0,NaN,15.0,45.0,A,92,53.000000
5,1006,Student_6,2.0,61.0,58.0,98.0,B,92,54.750000
6,1007,Student_7,NaN,98.0,92.0,62.0,A,96,84.000000
7,1008,Student_8,29.0,85.0,58.0,31.0,F,71,50.750000
8,1009,Student_9,63.0,64.0,89.0,66.0,F,62,70.500000
9,1010,Student_10,32.0,46.0,18.0,24.0,A,60,30.000000
10,1011,Student_11,21.0,0.0,70.0,53.0,F,92,36.000000
11,1012,Student_12,NaN,13.0,32.0,45.0,F,99,30.000000
12,1013,Student_13,NaN,8.0,38.0,NaN,F,69,23.000000
13,1014,Student_14,41.0,89.0,0.0,85.0,C,88,53.750000
14,1015,Student_15,NaN,NaN,56.0,26.0,D,72,41.000000
15,1016,Student_16,14.0,62.0,22.0,89.0,B,71,46.750000
16,1017,Student_17,46.0,51.0,41.0,32.0,C,90,42.500000
17,1018,Student_18,54.0,3.0,15.0,47.0,F,61,29.750000
18,1019,Student_19,2.0,22.0,59.0,41.0,A,94,31.000000
19,1020,Student_20,6.0,14.0,0.0,98.0,F,82,29.500000
20,1021,Student_21,38.0,35.0,NaN,23.0,D,76,32.000000
21,1022,Student_22,NaN,70.0,36.0,6.0,F,85,37.333333
22,1023,Student_23,13.0,85.0,8.0,44.0,A,67,37.500000
23,1024,Student_24,8.0,41.0,18.0,7.0,D,88,18.500000
24,1025,Student_25,NaN,56.0,2.0,15.0,F,85,24.333333
25,1026,Student_26,91.0,27.0,53.0,NaN,D,69,57.000000
26,1027,Student_27,70.0,43.0,23.0,14.0,B,85,37.500000
27,1028,Student_28,7.0,61.0,71.0,65.0,B,93,51.000000
28,1029,Student_29,NaN,91.0,83.0,62.0,F,66,78.666667
29,1030,Student_30,35.0,61.0,88.0,NaN,D,63,61.333333
30,1031,Student_31,3.0,26.0,92.0,62.0,A,70,45.750000
31,1032,Student_32,5.0,76.0,81.0,21.0,F,88,45.750000
32,1033,Student_33,3.0,69.0,34.0,85.0,B,95,47.750000
33,1034,Student_34,62.0,8.0,40.0,41.0,B,84,37.750000
34,1035,Student_35,43.0,96.0,67.0,53.0,F,80,64.750000
35,1036,Student_36,61.0,43.0,20.0,96.0,D,95,55.000000
36,1037,Student_37,94.0,58.0,7.0,59.0,B,69,54.500000
37,1038,Student_38,71.0,95.0,16.0,4.0,D,96,46.500000
38,1039,Student_39,61.0,51.0,47.0,5.0,B,68,41.000000
39,1040,Student_40,79.0,57.0,NaN,NaN,B,83,68.000000
40,1041,Student_41,52.0,38.0,21.0,46.0,C,94,39.250000
41,1042,Student_42,88.0,55.0,37.0,39.0,B,94,54.750000
42,1043,Student_43,40.0,NaN,50.0,12.0,A,95,34.000000
43,1044,Student_44,44.0,1.0,26.0,29.0,F,77,25.000000
44,1045,Student_45,NaN,86.0,20.0,NaN,F,98,53.000000
45,1046,Student_46,87.0,96.0,27.0,18.0,D,91,57.000000
46,1047,Student_47,7.0,1.0,96.0,54.0,B,83,39.500000
47,1048,Student_48,NaN,89.0,60.0,89.0,A,82,79.333333
48,1049,Student_49,80.0,31.0,3.0,22.0,D,91,34.000000
49,1050,Student_50,34.0,54.0,NaN,11.0,C,96,33.000000

## Q3.3: Missing Value Handling

#### Fill missing values in Math, Science, and English with their respective column means.

In [7]:
df.isnull().sum()

StudentID                0
Name                     0
Math                    10
Science                  3
English                  3
History                  5
Grade                    0
AttendancePercentage     0
Avg_score                0
dtype: int64

In [8]:
df['Math'].fillna(df['Math'].mean(), inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14988\3025746023.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Math'].fillna(df['Math'].mean(), inplace=True)

In [9]:
df['Science'].fillna(df['Science'].mean(), inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14988\2374971838.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Science'].fillna(df['Science'].mean(), inplace=True)

In [10]:
df['English'].fillna(df['English'].mean(), inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14988\259178685.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['English'].fillna(df['English'].mean(), inplace=True)

In [12]:
df['History'].fillna(df['History'].mean(), inplace=True)

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14988\2668831522.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['History'].fillna(df['History'].mean(), inplace=True)

In [13]:
df.isnull().sum()

StudentID               0
Name                    0
Math                    0
Science                 0
English                 0
History                 0
Grade                   0
AttendancePercentage    0
Avg_score               0
dtype: int64

In [14]:
df

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score
0,1001,Student_1,92.00,4.000000,16.000000,16.000000,F,79,32.000000
1,1002,Student_2,71.00,40.000000,23.000000,29.000000,A,83,40.750000
2,1003,Student_3,82.00,72.000000,97.000000,5.000000,B,71,64.000000
3,1004,Student_4,45.75,33.000000,10.000000,36.000000,B,94,26.333333
4,1005,Student_5,99.00,50.319149,15.000000,45.000000,A,92,53.000000
5,1006,Student_6,2.00,61.000000,58.000000,98.000000,B,92,54.750000
6,1007,Student_7,45.75,98.000000,92.000000,62.000000,A,96,84.000000
7,1008,Student_8,29.00,85.000000,58.000000,31.000000,F,71,50.750000
8,1009,Student_9,63.00,64.000000,89.000000,66.000000,F,62,70.500000
9,1010,Student_10,32.00,46.000000,18.000000,24.000000,A,60,30.000000
10,1011,Student_11,21.00,0.000000,70.000000,53.000000,F,92,36.000000
11,1012,Student_12,45.75,13.000000,32.000000,45.000000,F,99,30.000000
12,1013,Student_13,45.75,8.000000,38.000000,42.444444,F,69,23.000000
13,1014,Student_14,41.00,89.000000,0.000000,85.000000,C,88,53.750000
14,1015,Student_15,45.75,50.319149,56.000000,26.000000,D,72,41.000000
15,1016,Student_16,14.00,62.000000,22.000000,89.000000,B,71,46.750000
16,1017,Student_17,46.00,51.000000,41.000000,32.000000,C,90,42.500000
17,1018,Student_18,54.00,3.000000,15.000000,47.000000,F,61,29.750000
18,1019,Student_19,2.00,22.000000,59.000000,41.000000,A,94,31.000000
19,1020,Student_20,6.00,14.000000,0.000000,98.000000,F,82,29.500000
20,1021,Student_21,38.00,35.000000,41.170213,23.000000,D,76,32.000000
21,1022,Student_22,45.75,70.000000,36.000000,6.000000,F,85,37.333333
22,1023,Student_23,13.00,85.000000,8.000000,44.000000,A,67,37.500000
23,1024,Student_24,8.00,41.000000,18.000000,7.000000,D,88,18.500000
24,1025,Student_25,45.75,56.000000,2.000000,15.000000,F,85,24.333333
25,1026,Student_26,91.00,27.000000,53.000000,42.444444,D,69,57.000000
26,1027,Student_27,70.00,43.000000,23.000000,14.000000,B,85,37.500000
27,1028,Student_28,7.00,61.000000,71.000000,65.000000,B,93,51.000000
28,1029,Student_29,45.75,91.000000,83.000000,62.000000,F,66,78.666667
29,1030,Student_30,35.00,61.000000,88.000000,42.444444,D,63,61.333333
30,1031,Student_31,3.00,26.000000,92.000000,62.000000,A,70,45.750000
31,1032,Student_32,5.00,76.000000,81.000000,21.000000,F,88,45.750000
32,1033,Student_33,3.00,69.000000,34.000000,85.000000,B,95,47.750000
33,1034,Student_34,62.00,8.000000,40.000000,41.000000,B,84,37.750000
34,1035,Student_35,43.00,96.000000,67.000000,53.000000,F,80,64.750000
35,1036,Student_36,61.00,43.000000,20.000000,96.000000,D,95,55.000000
36,1037,Student_37,94.00,58.000000,7.000000,59.000000,B,69,54.500000
37,1038,Student_38,71.00,95.000000,16.000000,4.000000,D,96,46.500000
38,1039,Student_39,61.00,51.000000,47.000000,5.000000,B,68,41.000000
39,1040,Student_40,79.00,57.000000,41.170213,42.444444,B,83,68.000000
40,1041,Student_41,52.00,38.000000,21.000000,46.000000,C,94,39.250000
41,1042,Student_42,88.00,55.000000,37.000000,39.000000,B,94,54.750000
42,1043,Student_43,40.00,50.319149,50.000000,12.000000,A,95,34.000000
43,1044,Student_44,44.00,1.000000,26.000000,29.000000,F,77,25.000000
44,1045,Student_45,45.75,86.000000,20.000000,42.444444,F,98,53.000000
45,1046,Student_46,87.00,96.000000,27.000000,18.000000,D,91,57.000000
46,1047,Student_47,7.00,1.000000,96.000000,54.000000,B,83,39.500000
47,1048,Student_48,45.75,89.000000,60.000000,89.000000,A,82,79.333333
48,1049,Student_49,80.00,31.000000,3.000000,22.000000,D,91,34.000000
49,1050,Student_50,34.00,54.000000,41.170213,11.000000,C,96,33.000000

## Q3.4: Filtering by Performance

#### Filter students with an average score above the overall mean and display their names and average scores.

In [15]:
overall_mean=df['Avg_score'].mean()
overall_mean

np.float64(45.20166666666666)

In [16]:
above_mean=df[df['Avg_score']>overall_mean]
above_mean

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score
2,1003,Student_3,82.00,72.000000,97.000000,5.000000,B,71,64.000000
4,1005,Student_5,99.00,50.319149,15.000000,45.000000,A,92,53.000000
5,1006,Student_6,2.00,61.000000,58.000000,98.000000,B,92,54.750000
6,1007,Student_7,45.75,98.000000,92.000000,62.000000,A,96,84.000000
7,1008,Student_8,29.00,85.000000,58.000000,31.000000,F,71,50.750000
8,1009,Student_9,63.00,64.000000,89.000000,66.000000,F,62,70.500000
13,1014,Student_14,41.00,89.000000,0.000000,85.000000,C,88,53.750000
15,1016,Student_16,14.00,62.000000,22.000000,89.000000,B,71,46.750000
25,1026,Student_26,91.00,27.000000,53.000000,42.444444,D,69,57.000000
27,1028,Student_28,7.00,61.000000,71.000000,65.000000,B,93,51.000000
28,1029,Student_29,45.75,91.000000,83.000000,62.000000,F,66,78.666667
29,1030,Student_30,35.00,61.000000,88.000000,42.444444,D,63,61.333333
30,1031,Student_31,3.00,26.000000,92.000000,62.000000,A,70,45.750000
31,1032,Student_32,5.00,76.000000,81.000000,21.000000,F,88,45.750000
32,1033,Student_33,3.00,69.000000,34.000000,85.000000,B,95,47.750000
34,1035,Student_35,43.00,96.000000,67.000000,53.000000,F,80,64.750000
35,1036,Student_36,61.00,43.000000,20.000000,96.000000,D,95,55.000000
36,1037,Student_37,94.00,58.000000,7.000000,59.000000,B,69,54.500000
37,1038,Student_38,71.00,95.000000,16.000000,4.000000,D,96,46.500000
39,1040,Student_40,79.00,57.000000,41.170213,42.444444,B,83,68.000000
41,1042,Student_42,88.00,55.000000,37.000000,39.000000,B,94,54.750000
44,1045,Student_45,45.75,86.000000,20.000000,42.444444,F,98,53.000000
45,1046,Student_46,87.00,96.000000,27.000000,18.000000,D,91,57.000000
47,1048,Student_48,45.75,89.000000,60.000000,89.000000,A,82,79.333333

In [17]:
print(f"Overall Average Score: {overall_mean:.2f}")
print(f"\nStudents Above Average ({len(above_mean)} students):")
print(above_mean[['Name', 'Avg_score']].sort_values('Avg_score', ascending=False))

Overall Average Score: 45.20

Students Above Average (24 students):
          Name  Avg_score
6    Student_7  84.000000
47  Student_48  79.333333
28  Student_29  78.666667
8    Student_9  70.500000
39  Student_40  68.000000
34  Student_35  64.750000
2    Student_3  64.000000
29  Student_30  61.333333
25  Student_26  57.000000
45  Student_46  57.000000
35  Student_36  55.000000
41  Student_42  54.750000
5    Student_6  54.750000
36  Student_37  54.500000
13  Student_14  53.750000
4    Student_5  53.000000
44  Student_45  53.000000
27  Student_28  51.000000
7    Student_8  50.750000
32  Student_33  47.750000
15  Student_16  46.750000
37  Student_38  46.500000
30  Student_31  45.750000
31  Student_32  45.750000

## Q3.5: Label-based Selection (loc)

#### Use loc[] to update a specific student's Math score (e.g., StudentID 1001) to a new value.

In [18]:
student_id=1001
df.loc[df['StudentID'] == student_id , 'Math'] = 82
df

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score
0,1001,Student_1,82.00,4.000000,16.000000,16.000000,F,79,32.000000
1,1002,Student_2,71.00,40.000000,23.000000,29.000000,A,83,40.750000
2,1003,Student_3,82.00,72.000000,97.000000,5.000000,B,71,64.000000
3,1004,Student_4,45.75,33.000000,10.000000,36.000000,B,94,26.333333
4,1005,Student_5,99.00,50.319149,15.000000,45.000000,A,92,53.000000
5,1006,Student_6,2.00,61.000000,58.000000,98.000000,B,92,54.750000
6,1007,Student_7,45.75,98.000000,92.000000,62.000000,A,96,84.000000
7,1008,Student_8,29.00,85.000000,58.000000,31.000000,F,71,50.750000
8,1009,Student_9,63.00,64.000000,89.000000,66.000000,F,62,70.500000
9,1010,Student_10,32.00,46.000000,18.000000,24.000000,A,60,30.000000
10,1011,Student_11,21.00,0.000000,70.000000,53.000000,F,92,36.000000
11,1012,Student_12,45.75,13.000000,32.000000,45.000000,F,99,30.000000
12,1013,Student_13,45.75,8.000000,38.000000,42.444444,F,69,23.000000
13,1014,Student_14,41.00,89.000000,0.000000,85.000000,C,88,53.750000
14,1015,Student_15,45.75,50.319149,56.000000,26.000000,D,72,41.000000
15,1016,Student_16,14.00,62.000000,22.000000,89.000000,B,71,46.750000
16,1017,Student_17,46.00,51.000000,41.000000,32.000000,C,90,42.500000
17,1018,Student_18,54.00,3.000000,15.000000,47.000000,F,61,29.750000
18,1019,Student_19,2.00,22.000000,59.000000,41.000000,A,94,31.000000
19,1020,Student_20,6.00,14.000000,0.000000,98.000000,F,82,29.500000
20,1021,Student_21,38.00,35.000000,41.170213,23.000000,D,76,32.000000
21,1022,Student_22,45.75,70.000000,36.000000,6.000000,F,85,37.333333
22,1023,Student_23,13.00,85.000000,8.000000,44.000000,A,67,37.500000
23,1024,Student_24,8.00,41.000000,18.000000,7.000000,D,88,18.500000
24,1025,Student_25,45.75,56.000000,2.000000,15.000000,F,85,24.333333
25,1026,Student_26,91.00,27.000000,53.000000,42.444444,D,69,57.000000
26,1027,Student_27,70.00,43.000000,23.000000,14.000000,B,85,37.500000
27,1028,Student_28,7.00,61.000000,71.000000,65.000000,B,93,51.000000
28,1029,Student_29,45.75,91.000000,83.000000,62.000000,F,66,78.666667
29,1030,Student_30,35.00,61.000000,88.000000,42.444444,D,63,61.333333
30,1031,Student_31,3.00,26.000000,92.000000,62.000000,A,70,45.750000
31,1032,Student_32,5.00,76.000000,81.000000,21.000000,F,88,45.750000
32,1033,Student_33,3.00,69.000000,34.000000,85.000000,B,95,47.750000
33,1034,Student_34,62.00,8.000000,40.000000,41.000000,B,84,37.750000
34,1035,Student_35,43.00,96.000000,67.000000,53.000000,F,80,64.750000
35,1036,Student_36,61.00,43.000000,20.000000,96.000000,D,95,55.000000
36,1037,Student_37,94.00,58.000000,7.000000,59.000000,B,69,54.500000
37,1038,Student_38,71.00,95.000000,16.000000,4.000000,D,96,46.500000
38,1039,Student_39,61.00,51.000000,47.000000,5.000000,B,68,41.000000
39,1040,Student_40,79.00,57.000000,41.170213,42.444444,B,83,68.000000
40,1041,Student_41,52.00,38.000000,21.000000,46.000000,C,94,39.250000
41,1042,Student_42,88.00,55.000000,37.000000,39.000000,B,94,54.750000
42,1043,Student_43,40.00,50.319149,50.000000,12.000000,A,95,34.000000
43,1044,Student_44,44.00,1.000000,26.000000,29.000000,F,77,25.000000
44,1045,Student_45,45.75,86.000000,20.000000,42.444444,F,98,53.000000
45,1046,Student_46,87.00,96.000000,27.000000,18.000000,D,91,57.000000
46,1047,Student_47,7.00,1.000000,96.000000,54.000000,B,83,39.500000
47,1048,Student_48,45.75,89.000000,60.000000,89.000000,A,82,79.333333
48,1049,Student_49,80.00,31.000000,3.000000,22.000000,D,91,34.000000
49,1050,Student_50,34.00,54.000000,41.170213,11.000000,C,96,33.000000

In [19]:
print(f"Updated Math score for StudentID {student_id}:")
print(df.loc[df['StudentID'] == student_id, ['Name', 'Math', 'Avg_score']])

Updated Math score for StudentID 1001:
        Name  Math  Avg_score
0  Student_1  82.0       32.0

## Q3.6: Integer-based Selection (iloc)

#### Use iloc[] to select the first 10 rows and the last 3 columns, display them

In [20]:
data=df.iloc[0:10, 3:] # It is used to select the rows from 0 to 9 and columns from 3 to last
data

     Science  English  History Grade  AttendancePercentage  Avg_score
0   4.000000     16.0     16.0     F                    79  32.000000
1  40.000000     23.0     29.0     A                    83  40.750000
2  72.000000     97.0      5.0     B                    71  64.000000
3  33.000000     10.0     36.0     B                    94  26.333333
4  50.319149     15.0     45.0     A                    92  53.000000
5  61.000000     58.0     98.0     B                    92  54.750000
6  98.000000     92.0     62.0     A                    96  84.000000
7  85.000000     58.0     31.0     F                    71  50.750000
8  64.000000     89.0     66.0     F                    62  70.500000
9  46.000000     18.0     24.0     A                    60  30.000000

In [21]:
subset= df.iloc[0:10, -3:] # It is used to select the rows from 0 to 9 and columns last 3 rows only

In [22]:
print("First 10 Rows,last 3 Columns")
print(subset)

First 10 Rows,last 3 Columns
  Grade  AttendancePercentage  Avg_score
0     F                    79  32.000000
1     A                    83  40.750000
2     B                    71  64.000000
3     B                    94  26.333333
4     A                    92  53.000000
5     B                    92  54.750000
6     A                    96  84.000000
7     F                    71  50.750000
8     F                    62  70.500000
9     A                    60  30.000000

## Q3.7: Sorting

#### Sort students by AttendancePercentage in descending order and display the top 5

In [23]:
sort=df.sort_values(by='AttendancePercentage',ascending=False)
sort.head()

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score
11,1012,Student_12,45.75,13.0,32.000000,45.000000,F,99,30.0
44,1045,Student_45,45.75,86.0,20.000000,42.444444,F,98,53.0
37,1038,Student_38,71.00,95.0,16.000000,4.000000,D,96,46.5
49,1050,Student_50,34.00,54.0,41.170213,11.000000,C,96,33.0
6,1007,Student_7,45.75,98.0,92.000000,62.000000,A,96,84.0

In [24]:
top_attendance = df.nlargest(5, 'AttendancePercentage')
print("Top 5 Students by Attendance:")
print(top_attendance[['Name', 'AttendancePercentage', 'Grade']])

Top 5 Students by Attendance:
          Name  AttendancePercentage Grade
11  Student_12                    99     F
44  Student_45                    98     F
6    Student_7                    96     A
37  Student_38                    96     D
49  Student_50                    96     C

## Q3.8: Conditional Column Creation

#### Create a new column 'PassFail' where 'Pass' if average score > 50, else 'Fail'

In [52]:
# lambda- It is a nameless function to written in one line
# apply- to perform a custom operation on each value or rows or columns

In [25]:
df['PassFail'] = df['Avg_score'].apply(lambda x: 'Pass' if x > 50 else 'Fail')
print("Pass/Fail Distribution:")
print(df['PassFail'].value_counts())
print(df[['Name', 'Avg_score', 'PassFail']].head(10))

Pass/Fail Distribution:
PassFail
Fail    31
Pass    19
Name: count, dtype: int64
         Name  Avg_score PassFail
0   Student_1  32.000000     Fail
1   Student_2  40.750000     Fail
2   Student_3  64.000000     Pass
3   Student_4  26.333333     Fail
4   Student_5  53.000000     Pass
5   Student_6  54.750000     Pass
6   Student_7  84.000000     Pass
7   Student_8  50.750000     Pass
8   Student_9  70.500000     Pass
9  Student_10  30.000000     Fail

## Q3.9: Duplicate Removal

#### Identify and remove duplicate rows (if any) based on all columns.

In [26]:
duplicates=df.duplicated().sum()
duplicates

np.int64(0)

## Q3.10: Data Export

#### Export the cleaned and processed data to student_scores_cleaned.csv.

In [42]:
cleaned=df.to_csv('student_scores_cleaned.csv',index=False)

## Challenge Extension

### Challenge 1
#### Create a grade categorization (A, B, C, D, F) based on average scores

In [33]:
# lambda- It is a nameless function to written in one line
# apply- to perform a custom operation on each value or rows or columns
df['Grade_Name'] = df['Avg_score'].apply(
    lambda x: 'A' if x >= 90 else
              'B' if x >= 75 else
              'C' if x >= 60 else
              'D' if x >= 50 else 'F'
)
print(df[['Name', 'Avg_score', 'Grade']])
df

          Name  Avg_score Grade
0    Student_1  32.000000     F
1    Student_2  40.750000     F
2    Student_3  64.000000     C
3    Student_4  26.333333     F
4    Student_5  53.000000     D
5    Student_6  54.750000     D
6    Student_7  84.000000     B
7    Student_8  50.750000     D
8    Student_9  70.500000     C
9   Student_10  30.000000     F
10  Student_11  36.000000     F
11  Student_12  30.000000     F
12  Student_13  23.000000     F
13  Student_14  53.750000     D
14  Student_15  41.000000     F
15  Student_16  46.750000     F
16  Student_17  42.500000     F
17  Student_18  29.750000     F
18  Student_19  31.000000     F
19  Student_20  29.500000     F
20  Student_21  32.000000     F
21  Student_22  37.333333     F
22  Student_23  37.500000     F
23  Student_24  18.500000     F
24  Student_25  24.333333     F
25  Student_26  57.000000     D
26  Student_27  37.500000     F
27  Student_28  51.000000     D
28  Student_29  78.666667     B
29  Student_30  61.333333     C
30  Student_31  45.750000     F
31  Student_32  45.750000     F
32  Student_33  47.750000     F
33  Student_34  37.750000     F
34  Student_35  64.750000     C
35  Student_36  55.000000     D
36  Student_37  54.500000     D
37  Student_38  46.500000     F
38  Student_39  41.000000     F
39  Student_40  68.000000     C
40  Student_41  39.250000     F
41  Student_42  54.750000     D
42  Student_43  34.000000     F
43  Student_44  25.000000     F
44  Student_45  53.000000     D
45  Student_46  57.000000     D
46  Student_47  39.500000     F
47  Student_48  79.333333     B
48  Student_49  34.000000     F
49  Student_50  33.000000     F

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score,PassFail,Grade_Category,Grade_Name
0,1001,Student_1,82.00,4.000000,16.000000,16.000000,F,79,32.000000,Fail,F,F
1,1002,Student_2,71.00,40.000000,23.000000,29.000000,F,83,40.750000,Fail,F,F
2,1003,Student_3,82.00,72.000000,97.000000,5.000000,C,71,64.000000,Pass,C,C
3,1004,Student_4,45.75,33.000000,10.000000,36.000000,F,94,26.333333,Fail,F,F
4,1005,Student_5,99.00,50.319149,15.000000,45.000000,D,92,53.000000,Pass,D,D
5,1006,Student_6,2.00,61.000000,58.000000,98.000000,D,92,54.750000,Pass,D,D
6,1007,Student_7,45.75,98.000000,92.000000,62.000000,B,96,84.000000,Pass,B,B
7,1008,Student_8,29.00,85.000000,58.000000,31.000000,D,71,50.750000,Pass,D,D
8,1009,Student_9,63.00,64.000000,89.000000,66.000000,C,62,70.500000,Pass,C,C
9,1010,Student_10,32.00,46.000000,18.000000,24.000000,F,60,30.000000,Fail,F,F
10,1011,Student_11,21.00,0.000000,70.000000,53.000000,F,92,36.000000,Fail,F,F
11,1012,Student_12,45.75,13.000000,32.000000,45.000000,F,99,30.000000,Fail,F,F
12,1013,Student_13,45.75,8.000000,38.000000,42.444444,F,69,23.000000,Fail,F,F
13,1014,Student_14,41.00,89.000000,0.000000,85.000000,D,88,53.750000,Pass,D,D
14,1015,Student_15,45.75,50.319149,56.000000,26.000000,F,72,41.000000,Fail,F,F
15,1016,Student_16,14.00,62.000000,22.000000,89.000000,F,71,46.750000,Fail,F,F
16,1017,Student_17,46.00,51.000000,41.000000,32.000000,F,90,42.500000,Fail,F,F
17,1018,Student_18,54.00,3.000000,15.000000,47.000000,F,61,29.750000,Fail,F,F
18,1019,Student_19,2.00,22.000000,59.000000,41.000000,F,94,31.000000,Fail,F,F
19,1020,Student_20,6.00,14.000000,0.000000,98.000000,F,82,29.500000,Fail,F,F
20,1021,Student_21,38.00,35.000000,41.170213,23.000000,F,76,32.000000,Fail,F,F
21,1022,Student_22,45.75,70.000000,36.000000,6.000000,F,85,37.333333,Fail,F,F
22,1023,Student_23,13.00,85.000000,8.000000,44.000000,F,67,37.500000,Fail,F,F
23,1024,Student_24,8.00,41.000000,18.000000,7.000000,F,88,18.500000,Fail,F,F
24,1025,Student_25,45.75,56.000000,2.000000,15.000000,F,85,24.333333,Fail,F,F
25,1026,Student_26,91.00,27.000000,53.000000,42.444444,D,69,57.000000,Pass,D,D
26,1027,Student_27,70.00,43.000000,23.000000,14.000000,F,85,37.500000,Fail,F,F
27,1028,Student_28,7.00,61.000000,71.000000,65.000000,D,93,51.000000,Pass,D,D
28,1029,Student_29,45.75,91.000000,83.000000,62.000000,B,66,78.666667,Pass,B,B
29,1030,Student_30,35.00,61.000000,88.000000,42.444444,C,63,61.333333,Pass,C,C
30,1031,Student_31,3.00,26.000000,92.000000,62.000000,F,70,45.750000,Fail,F,F
31,1032,Student_32,5.00,76.000000,81.000000,21.000000,F,88,45.750000,Fail,F,F
32,1033,Student_33,3.00,69.000000,34.000000,85.000000,F,95,47.750000,Fail,F,F
33,1034,Student_34,62.00,8.000000,40.000000,41.000000,F,84,37.750000,Fail,F,F
34,1035,Student_35,43.00,96.000000,67.000000,53.000000,C,80,64.750000,Pass,C,C
35,1036,Student_36,61.00,43.000000,20.000000,96.000000,D,95,55.000000,Pass,D,D
36,1037,Student_37,94.00,58.000000,7.000000,59.000000,D,69,54.500000,Pass,D,D
37,1038,Student_38,71.00,95.000000,16.000000,4.000000,F,96,46.500000,Fail,F,F
38,1039,Student_39,61.00,51.000000,47.000000,5.000000,F,68,41.000000,Fail,F,F
39,1040,Student_40,79.00,57.000000,41.170213,42.444444,C,83,68.000000,Pass,C,C
40,1041,Student_41,52.00,38.000000,21.000000,46.000000,F,94,39.250000,Fail,F,F
41,1042,Student_42,88.00,55.000000,37.000000,39.000000,D,94,54.750000,Pass,D,D
42,1043,Student_43,40.00,50.319149,50.000000,12.000000,F,95,34.000000,Fail,F,F
43,1044,Student_44,44.00,1.000000,26.000000,29.000000,F,77,25.000000,Fail,F,F
44,1045,Student_45,45.75,86.000000,20.000000,42.444444,D,98,53.000000,Pass,D,D
45,1046,Student_46,87.00,96.000000,27.000000,18.000000,D,91,57.000000,Pass,D,D
46,1047,Student_47,7.00,1.000000,96.000000,54.000000,F,83,39.500000,Fail,F,F
47,1048,Student_48,45.75,89.000000,60.000000,89.000000,B,82,79.333333,Pass,B,B
48,1049,Student_49,80.00,31.000000,3.000000,22.000000,F,91,34.000000,Fail,F,F
49,1050,Student_50,34.00,54.000000,41.170213,11.000000,F,96,33.000000,Fail,F,F

In [34]:
def get_grade(Avg_score):
    if Avg_score >= 90:
        return 'A'
    if Avg_score >= 75:
        return 'B'
    if Avg_score >= 60:
        return 'C'
    if Avg_score >= 50:
        return 'D'
    else:
        return 'F'

In [35]:
df['Grade_Category'] = df['Avg_score'].apply(lambda x: get_grade(x))
df

,StudentID,Name,Math,Science,English,History,Grade,AttendancePercentage,Avg_score,PassFail,Grade_Category,Grade_Name
0,1001,Student_1,82.00,4.000000,16.000000,16.000000,F,79,32.000000,Fail,F,F
1,1002,Student_2,71.00,40.000000,23.000000,29.000000,F,83,40.750000,Fail,F,F
2,1003,Student_3,82.00,72.000000,97.000000,5.000000,C,71,64.000000,Pass,C,C
3,1004,Student_4,45.75,33.000000,10.000000,36.000000,F,94,26.333333,Fail,F,F
4,1005,Student_5,99.00,50.319149,15.000000,45.000000,D,92,53.000000,Pass,D,D
5,1006,Student_6,2.00,61.000000,58.000000,98.000000,D,92,54.750000,Pass,D,D
6,1007,Student_7,45.75,98.000000,92.000000,62.000000,B,96,84.000000,Pass,B,B
7,1008,Student_8,29.00,85.000000,58.000000,31.000000,D,71,50.750000,Pass,D,D
8,1009,Student_9,63.00,64.000000,89.000000,66.000000,C,62,70.500000,Pass,C,C
9,1010,Student_10,32.00,46.000000,18.000000,24.000000,F,60,30.000000,Fail,F,F
10,1011,Student_11,21.00,0.000000,70.000000,53.000000,F,92,36.000000,Fail,F,F
11,1012,Student_12,45.75,13.000000,32.000000,45.000000,F,99,30.000000,Fail,F,F
12,1013,Student_13,45.75,8.000000,38.000000,42.444444,F,69,23.000000,Fail,F,F
13,1014,Student_14,41.00,89.000000,0.000000,85.000000,D,88,53.750000,Pass,D,D
14,1015,Student_15,45.75,50.319149,56.000000,26.000000,F,72,41.000000,Fail,F,F
15,1016,Student_16,14.00,62.000000,22.000000,89.000000,F,71,46.750000,Fail,F,F
16,1017,Student_17,46.00,51.000000,41.000000,32.000000,F,90,42.500000,Fail,F,F
17,1018,Student_18,54.00,3.000000,15.000000,47.000000,F,61,29.750000,Fail,F,F
18,1019,Student_19,2.00,22.000000,59.000000,41.000000,F,94,31.000000,Fail,F,F
19,1020,Student_20,6.00,14.000000,0.000000,98.000000,F,82,29.500000,Fail,F,F
20,1021,Student_21,38.00,35.000000,41.170213,23.000000,F,76,32.000000,Fail,F,F
21,1022,Student_22,45.75,70.000000,36.000000,6.000000,F,85,37.333333,Fail,F,F
22,1023,Student_23,13.00,85.000000,8.000000,44.000000,F,67,37.500000,Fail,F,F
23,1024,Student_24,8.00,41.000000,18.000000,7.000000,F,88,18.500000,Fail,F,F
24,1025,Student_25,45.75,56.000000,2.000000,15.000000,F,85,24.333333,Fail,F,F
25,1026,Student_26,91.00,27.000000,53.000000,42.444444,D,69,57.000000,Pass,D,D
26,1027,Student_27,70.00,43.000000,23.000000,14.000000,F,85,37.500000,Fail,F,F
27,1028,Student_28,7.00,61.000000,71.000000,65.000000,D,93,51.000000,Pass,D,D
28,1029,Student_29,45.75,91.000000,83.000000,62.000000,B,66,78.666667,Pass,B,B
29,1030,Student_30,35.00,61.000000,88.000000,42.444444,C,63,61.333333,Pass,C,C
30,1031,Student_31,3.00,26.000000,92.000000,62.000000,F,70,45.750000,Fail,F,F
31,1032,Student_32,5.00,76.000000,81.000000,21.000000,F,88,45.750000,Fail,F,F
32,1033,Student_33,3.00,69.000000,34.000000,85.000000,F,95,47.750000,Fail,F,F
33,1034,Student_34,62.00,8.000000,40.000000,41.000000,F,84,37.750000,Fail,F,F
34,1035,Student_35,43.00,96.000000,67.000000,53.000000,C,80,64.750000,Pass,C,C
35,1036,Student_36,61.00,43.000000,20.000000,96.000000,D,95,55.000000,Pass,D,D
36,1037,Student_37,94.00,58.000000,7.000000,59.000000,D,69,54.500000,Pass,D,D
37,1038,Student_38,71.00,95.000000,16.000000,4.000000,F,96,46.500000,Fail,F,F
38,1039,Student_39,61.00,51.000000,47.000000,5.000000,F,68,41.000000,Fail,F,F
39,1040,Student_40,79.00,57.000000,41.170213,42.444444,C,83,68.000000,Pass,C,C
40,1041,Student_41,52.00,38.000000,21.000000,46.000000,F,94,39.250000,Fail,F,F
41,1042,Student_42,88.00,55.000000,37.000000,39.000000,D,94,54.750000,Pass,D,D
42,1043,Student_43,40.00,50.319149,50.000000,12.000000,F,95,34.000000,Fail,F,F
43,1044,Student_44,44.00,1.000000,26.000000,29.000000,F,77,25.000000,Fail,F,F
44,1045,Student_45,45.75,86.000000,20.000000,42.444444,D,98,53.000000,Pass,D,D
45,1046,Student_46,87.00,96.000000,27.000000,18.000000,D,91,57.000000,Pass,D,D
46,1047,Student_47,7.00,1.000000,96.000000,54.000000,F,83,39.500000,Fail,F,F
47,1048,Student_48,45.75,89.000000,60.000000,89.000000,B,82,79.333333,Pass,B,B
48,1049,Student_49,80.00,31.000000,3.000000,22.000000,F,91,34.000000,Fail,F,F
49,1050,Student_50,34.00,54.000000,41.170213,11.000000,F,96,33.000000,Fail,F,F

In [36]:
bins = [0, 50, 60, 75, 90, 100]
labels = ['F', 'D', 'C', 'B', 'A']
#cut is used to convert the continuous numeric scores into categorical grades using predefined ranges
df['Grade'] = pd.cut(df['Avg_score'], bins=bins, labels=labels, right=False)
print(df[['Name', 'Avg_score', 'Grade']].head(10))

         Name  Avg_score Grade
0   Student_1  32.000000     F
1   Student_2  40.750000     F
2   Student_3  64.000000     C
3   Student_4  26.333333     F
4   Student_5  53.000000     D
5   Student_6  54.750000     D
6   Student_7  84.000000     B
7   Student_8  50.750000     D
8   Student_9  70.500000     C
9  Student_10  30.000000     F

## Challenge 2: 
#### Calculate z-scores for each subject and identify outlier students

In [37]:
# Calculate z-scores
subjects=df[['Math','Science','English','History']]
for subject in subjects:
    df[f"{subject}_z"] = ((df[subject] - df[subject].mean()) / df[subject].std())

In [38]:
outliers = df[(df['Math_z'].abs() > 3) |(df['Science_z'].abs() > 3) | (df['English_z'].abs() > 3)]
print("Outlier Students:")
print(outliers[['StudentID', 'Name','Math_z', 'Science_z', 'English_z']])

Outlier Students:
Empty DataFrame
Columns: [StudentID, Name, Math_z, Science_z, English_z]
Index: []

## Challenge 3
#### Generate a summary report by Grade (A, B, C, etc.) showing statistics.

In [39]:
grade_summary = df.groupby('Grade')['Avg_score'].agg(
    Student_Count='count',
    Average_Score='mean',
    Min_Score='min',
    Max_Score='max'
).reset_index()
print("Grade-wise Summary Report:")
print(grade_summary)

Grade-wise Summary Report:
  Grade  Student_Count  Average_Score  Min_Score  Max_Score
0     F             31      35.322581  18.500000      47.75
1     D             11      54.045455  50.750000      57.00
2     C              5      65.716667  61.333333      70.50
3     B              3      80.666667  78.666667      84.00
4     A              0            NaN        NaN        NaN

C:\Users\USER 10\AppData\Local\Temp\ipykernel_14988\1038353275.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grade_summary = df.groupby('Grade')['Avg_score'].agg(