# Day 5 – pandas DataFrame Creation & Basic Operations: 10 Questions
## Question 1
### Create a DataFrame for 5 students with columns: `name`, `age`, `maths`.
#### Print the DataFrame.
#### Print `info()` and `describe()`.

In [6]:
import pandas as pd
import numpy as np

In [7]:
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [20, 21, 19, 22, 20],
    "maths": [85, 78, 92, 88, 76]
}

In [10]:
df=pd.DataFrame(data)
df

      name  age  maths
0    Alice   20     85
1      Bob   21     78
2  Charlie   19     92
3    David   22     88
4      Eva   20     76

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   maths   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [12]:
df.describe()

             age      maths
count   5.000000   5.000000
mean   20.400000  83.800000
std     1.140175   6.723095
min    19.000000  76.000000
25%    20.000000  78.000000
50%    20.000000  85.000000
75%    21.000000  88.000000
max    22.000000  92.000000

## Question 2
### Create a DataFrame from:
### ```data = {'city': ['A', 'B', 'C', 'D'],'temp': [30, 22, 25, 28],'humidity': [65, 70, 68, 72]}```
#### Print first 3 rows.
#### Print only `city` and `temp`.

In [13]:
data = {
    'city': ['A', 'B', 'C', 'D'],
    'temp': [30, 22, 25, 28],
    'humidity': [65, 70, 68, 72]
}

In [14]:
df=pd.DataFrame(data)
df

  city  temp  humidity
0    A    30        65
1    B    22        70
2    C    25        68
3    D    28        72

In [15]:
df.head(3)

  city  temp  humidity
0    A    30        65
1    B    22        70
2    C    25        68

In [16]:
df.city

0    A
1    B
2    C
3    D
Name: city, dtype: object

In [17]:
df.temp

0    30
1    22
2    25
3    28
Name: temp, dtype: int64

## Question 3
### Add a new column `temp_f` to convert `temp` from Celsius to Fahrenheit.
#### Print the DataFrame.

In [18]:
df['temp_f']=df['temp']*9/5+32

In [19]:
df

  city  temp  humidity  temp_f
0    A    30        65    86.0
1    B    22        70    71.6
2    C    25        68    77.0
3    D    28        72    82.4

## Question 4
### For a DataFrame with numeric columns `A`, `B`, `C`, add:
#### `A_plus_B = A + B`
#### `C_squared = C ** 2`.

In [21]:
df = pd.DataFrame({
    'A': [2, 4, 6, 8],
    'B': [1, 3, 5, 7],
    'C': [3, 5, 7, 9]
})

In [22]:
df['A_plus_B']=df['A']+df['B']

In [23]:
df['C_squared']=df['C']**2

In [24]:
df

   A  B  C  A_plus_B  C_squared
0  2  1  3         3          9
1  4  3  5         7         25
2  6  5  7        11         49
3  8  7  9        15         81

## Question 5
### Create a DataFrame with at least 6 rows and 3 numeric columns.
#### Select rows where one column is greater than 50.
#### Select rows where another column is in `[10, 20, 30]`.

In [25]:
df = pd.DataFrame({
    'A': [45, 60, 75, 30, 90, 55],
    'B': [10, 20, 40, 30, 50, 20],
    'C': [5, 15, 25, 35, 45, 55]
})

In [26]:
df[df['A']>50]

    A   B   C
1  60  20  15
2  75  40  25
4  90  50  45
5  55  20  55

In [28]:
df.isin([10,20,30])

       A      B      C
0  False   True  False
1  False   True  False
2  False  False  False
3   True   True  False
4  False  False  False
5  False   True  False

In [30]:
df[df['B'].isin([10,20,30])]

    A   B   C
0  45  10   5
1  60  20  15
3  30  30  35
5  55  20  55

## Question 6
### Demonstrate row and column selection:
#### Select a single row by `.loc`.
#### Select a single row by `.iloc`.
#### Select a subset of rows and columns using `.loc`.

In [33]:
df.loc[0]

A    45
B    10
C     5
Name: 0, dtype: int64

In [34]:
df.iloc[-1]

A    55
B    20
C    55
Name: 5, dtype: int64

In [37]:
df.loc[1:3,'A':'C']

    A   B   C
1  60  20  15
2  75  40  25
3  30  30  35

In [38]:
df.loc[1:3,'C']

1    15
2    25
3    35
Name: C, dtype: int64

## Question 7
### Create a DataFrame with a `student_id` column.
#### Set `student_id` as index.
#### Reset the index back.

In [39]:
df = pd.DataFrame({
    'student_id': [101, 102, 103],
    'name': ['Alice', 'Bob', 'Charlie'],
    'marks': [85, 90, 78]
})

In [41]:
df.set_index('student_id')

               name  marks
student_id
101           Alice     85
102             Bob     90
103         Charlie     78

In [42]:
df.reset_index()

   index  student_id     name  marks
0      0         101    Alice     85
1      1         102      Bob     90
2      2         103  Charlie     78

## Question 8
### Given a DataFrame with `marks` column, compute and print:
#### Mean marks
#### Row with maximum marks.

In [43]:
df=pd.DataFrame({'marks': [85, 90, 78, 50, 67]})

In [44]:
df.mean()

marks    74.0
dtype: float64

In [47]:
df.loc[df['marks'].idxmax()]

marks    90
Name: 1, dtype: int64

## Question 9
### Create a DataFrame and demonstrate:
#### Renaming a column.
#### Dropping a column.
#### Dropping a row by index.

In [50]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [49]:
df.rename(columns={'A':'G'})

   G  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [51]:
df.drop(columns='C')

   A  B
0  1  4
1  2  5
2  3  6

In [52]:
df.drop(index=2)

   A  B  C
0  1  4  7
1  2  5  8

## Question 10
### Create a DataFrame with a column of strings.
#### Convert the column to uppercase.
#### Create a new column with the length of each string.

In [53]:
df = pd.DataFrame({'text': ['hello', 'world', 'pandas','oops']})

In [54]:
df

     text
0   hello
1   world
2  pandas
3    oops

In [57]:
df['upper']=df['text'].str.upper()
df

     text   upper
0   hello   HELLO
1   world   WORLD
2  pandas  PANDAS
3    oops    OOPS

In [58]:
df['length']=df['text'].str.len()
df

     text   upper  length
0   hello   HELLO       5
1   world   WORLD       5
2  pandas  PANDAS       6
3    oops    OOPS       4