# Day 9 – NumPy-Pandas Interoperability: 10 Questions
## Question 1
### Create a DataFrame of shape `(4, 3)` with integers 0–11.
#### Convert to NumPy array with `.to_numpy()`.
#### Print `dtype` and `shape`.

In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame(np.arange(0,12).reshape(4,3))
df

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [4]:
arr=df.to_numpy()
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.shape

(4, 3)

## Question 2
### Create a 2D NumPy array of shape `(3, 4)` and convert to DataFrame with column names `['c1', 'c2', 'c3', 'c4']`.
#### Print the DataFrame.

In [8]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
df=pd.DataFrame(arr,columns=['c1','c2','c3','c4'])
df

   c1  c2  c3  c4
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11

## Question 3
### For a numeric DataFrame column, compute mean and std using NumPy (`np.mean`, `np.std`) and pandas (`.mean()`, `.std()`).
#### Print both results.

In [11]:
df=pd.DataFrame({'marks':[20,40,60,80]})
df

   marks
0     20
1     40
2     60
3     80

In [12]:
#numpy
mean=np.mean(df['marks'])
mean

np.float64(50.0)

In [13]:
std=np.std(df['marks'])
std

22.360679774997898

In [16]:
#pandas
mean=df['marks'].mean()
mean

np.float64(50.0)

In [18]:
std=df['marks'].std()
std

25.81988897471611

## Question 4
### Extract underlying array from DataFrame using `.to_numpy()`.
#### Use `np.sum(axis=0)` and compare with `df.sum()`.

In [19]:
df = pd.DataFrame({
    'A': [10, 20, 30],
    'B': [40, 50, 60]
})

In [21]:
arr=df.to_numpy()
arr

array([[10, 40],
       [20, 50],
       [30, 60]])

In [24]:
sum=np.sum(arr,axis=0)
sum

array([ 60, 150])

In [26]:
sum=df.sum(axis=0)
sum

A     60
B    150
dtype: int64

## Question 5
### Create a DataFrame from a NumPy array.
#### Add column that is square of one column using NumPy.
#### Add boolean column that checks if another column > threshold.

In [27]:
arr = np.array([[2, 5],[4, 8],[6, 3]])

In [28]:
df = pd.DataFrame(arr, columns=['A', 'B'])

In [29]:
df['A_square']=np.square(df['A'])

In [30]:
threshold=5
df['threshold']=np.array(df['B'])>threshold

In [31]:
df

   A  B  A_square  threshold
0  2  5         4      False
1  4  8        16       True
2  6  3        36      False

## Question 6
### Demonstrate whether modifying array from `.to_numpy()` changes DataFrame (conceptual demonstration).

In [33]:
df = pd.DataFrame({'A': [1, 2, 3]})
arr = df.to_numpy()
arr[0, 0] = 100
arr

array([[100],
       [  2],
       [  3]])

## Question 7
### Create a Series from random NumPy array.
### Use `np.where` to create 1s where values > 0, else 0.
### Convert result to Series.

In [34]:
arr=np.random.randn(5)

In [35]:
result=np.where(arr>0,1,0)

In [36]:
series=pd.Series(result)
series

0    1
1    1
2    0
3    0
4    0
dtype: int64

## Question 8
### Take a DataFrame, get `.to_numpy()`, slice a submatrix.
#### Convert submatrix back to DataFrame.

In [37]:
df = pd.DataFrame({
    'A': [10, 20, 30, 40],
    'B': [50, 60, 70, 80],
    'C': [90, 100, 110, 120]
})

In [38]:
arr=df.to_numpy()
arr

array([[ 10,  50,  90],
       [ 20,  60, 100],
       [ 30,  70, 110],
       [ 40,  80, 120]])

In [40]:
sub_arr=arr[1:3,0:2]
sub_arr

array([[20, 60],
       [30, 70]])

In [41]:
sub_df=pd.DataFrame(sub_arr,columns=['A','B'])
sub_df

    A   B
0  20  60
1  30  70

## Question 9
### Use `np.where` on DataFrame marks column to create a `result` column (`"Pass"` if ≥40 else `"Fail"`).

In [42]:
df = pd.DataFrame({'marks': [35, 45, 60, 30, 80]})

In [44]:
df['result']=np.where(df['marks']>=40,'Pass','Fail')

In [45]:
df

   marks result
0     35   Fail
1     45   Pass
2     60   Pass
3     30   Fail
4     80   Pass

## Question 10
## Use NumPy to standardize a numeric column (z-score) and store in new column.

In [48]:
df['z-score']=(df['marks']-np.mean(df['marks']))/np.std(df['marks'])

In [49]:
df

   marks result   z-score
0     35   Fail -0.825723
1     45   Pass -0.275241
2     60   Pass  0.550482
3     30   Fail -1.100964
4     80   Pass  1.651446