# Day 8 – Merge, Join, Concat: 10 Questions
## Question 1
### Create `df_customers` (`customer_id`, `name`) and `df_orders` (`order_id`, `customer_id`).
#### Perform inner merge on `customer_id`.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_customers = pd.DataFrame({'customer_id': [1, 2, 3],'name': ['A', 'B', 'C']})
df_orders = pd.DataFrame({'order_id': [101, 102, 103],'customer_id': [1, 2, 2]})

In [3]:
merge=df_customers.merge(df_orders,on='customer_id',how='inner')

In [4]:
merge

   customer_id name  order_id
0            1    A       101
1            2    B       102
2            2    B       103

## Question 2
### Perform left and right merge on `customer_id` for these DataFrames.
#### Compare row counts.

In [9]:
left=df_customers.merge(df_orders,on='customer_id',how='left')
left

   customer_id name  order_id
0            1    A     101.0
1            2    B     102.0
2            2    B     103.0
3            3    C       NaN

In [10]:
right=df_customers.merge(df_orders,on='customer_id',how='right')
right

   customer_id name  order_id
0            1    A       101
1            2    B       102
2            2    B       103

In [11]:
print(f"Left_Rows:{len(left)},Right_Rows:{len(right)}")

Left_Rows:4,Right_Rows:3

## Question 3
### Create `df1(id, value1)` and `df2(id, value2)` with partially overlapping `id`.
#### Perform outer merge and print result.

In [12]:
df1 = pd.DataFrame({'id': [1, 2], 'value1': [10, 20]})
df2 = pd.DataFrame({'id': [2, 3], 'value2': [200, 300]})

In [14]:
merge_overlap=df1.merge(df2,on='id',how='outer')
merge_overlap

   id  value1  value2
0   1    10.0     NaN
1   2    20.0   200.0
2   3     NaN   300.0

## Question 4
### Create two monthly DataFrames with same columns.
#### Concatenate vertically and reset index.

In [24]:
m1 = pd.DataFrame({'id': [1, 2, 3],'sales': [100, 150, 200]})
m2 = pd.DataFrame({'id': [4, 5, 6],'sales': [120, 180, 210]})

In [25]:
df=pd.concat([m1,m2],ignore_index=True,axis=0)
df

   id  sales
0   1    100
1   2    150
2   3    200
3   4    120
4   5    180
5   6    210

## Question 5
### Create two DataFrames with same index but different columns.
#### Concatenate horizontally (`axis=1`).

In [26]:
m1 = pd.DataFrame({'id': [1, 2, 3],'sales': [100, 150, 200]})
m2 = pd.DataFrame({'customer_id': [4, 5, 6],'customer_sales': [120, 180, 210]})

In [27]:
df=pd.concat([m1,m2],ignore_index=True,axis=1)
df

   0    1  2    3
0  1  100  4  120
1  2  150  5  180
2  3  200  6  210

## Question 6
### Show how to add a new row to a DataFrame by concatenating with a single-row DataFrame.

In [2]:
m3=pd.DataFrame({'A':[5],'B':[6]})

In [31]:
df3=pd.concat([df,m3],ignore_index=True)

In [32]:
df3

     0      1    2      3    A    B
0  1.0  100.0  4.0  120.0  NaN  NaN
1  2.0  150.0  5.0  180.0  NaN  NaN
2  3.0  200.0  6.0  210.0  NaN  NaN
3  NaN    NaN  NaN    NaN  5.0  6.0

## Question 7
### Create two DataFrames where one has extra keys.
#### Left merge with `indicator=True`.
#### Filter rows available only in left.

In [33]:
df4 = pd.DataFrame({'key': [1, 2], 'A': ['x', 'y']})
df5 = pd.DataFrame({'key': [2, 3], 'B': ['p', 'q']})

In [35]:
merge=df4.merge(df5,on='key',how='left',indicator=True)
merge

   key  A    B     _merge
0    1  x  NaN  left_only
1    2  y    p       both

In [36]:
filter=merge[merge['_merge']=='left_only']

In [37]:
filter

   key  A    B     _merge
0    1  x  NaN  left_only

## Question 8
### Demonstrate merge on multiple keys, e.g. `['city', 'year']`.

In [38]:
df6 = pd.DataFrame({'city': ['A', 'A'], 'year': [2024, 2025], 'val1': [1, 2]})
df7 = pd.DataFrame({'city': ['A', 'B'], 'year': [2024, 2025], 'val2': [10, 20]})

In [42]:
merge1=df6.merge(df7,how='inner',on=['city','year'])
merge1

  city  year  val1  val2
0    A  2024     1    10

In [43]:
merge2=df6.merge(df7,how='left',on=['city','year'])
merge2

  city  year  val1  val2
0    A  2024     1  10.0
1    A  2025     2   NaN

## Question 9
### Create a product DataFrame and discount DataFrame.
#### Merge and compute final price after discount.

In [47]:
products = pd.DataFrame({'prod_id': [1, 2], 'price': [100, 200]})
disc = pd.DataFrame({'prod_id': [1, 2], 'discount': [0.1, 0.2]})

In [50]:
m=products.merge(disc,how='inner',on='prod_id')
m

   prod_id  price  discount
0        1    100       0.1
1        2    200       0.2

In [51]:
m['final_price']=m['price']*(1-m['discount'])
m

   prod_id  price  discount  final_price
0        1    100       0.1         90.0
1        2    200       0.2        160.0

## Question 10
### Use `pd.concat` with `keys` to create a hierarchical index for two DataFrames.

In [52]:
df8 = pd.DataFrame({'A': [10, 20]})
df9 = pd.DataFrame({'A': [30, 40]})

In [53]:
merge=pd.concat({'first':df8,'second':df9})
merge

           A
first  0  10
       1  20
second 0  30
       1  40