# Day 6 – Filtering, Sorting, Missing Data: 10 Questions

## Question 1
### Create a DataFrame of 6 employees: `emp_id`, `name`, `age`, `salary`, `dept`.
#### Filter employees with salary > 40000.
#### Filter employees from a given department with age < 30.

In [43]:
import pandas as pd
import numpy as np

In [44]:
df = pd.DataFrame({
    'emp_id': [1, 2, 3, 4, 5, 6],
    'name': ['A', 'B', 'C', 'D', 'E', 'F'],
    'age': [25, 32, 28, 29, 24, 35],
    'salary': [30000, 50000, 40000, 45000, 28000, 60000],
    'dept': ['HR', 'IT', 'IT', 'Sales', 'HR', 'IT']
})
df

   emp_id name  age  salary   dept
0       1    A   25   30000     HR
1       2    B   32   50000     IT
2       3    C   28   40000     IT
3       4    D   29   45000  Sales
4       5    E   24   28000     HR
5       6    F   35   60000     IT

In [45]:
df[df['salary']>40000]

   emp_id name  age  salary   dept
1       2    B   32   50000     IT
3       4    D   29   45000  Sales
5       6    F   35   60000     IT

In [46]:
print(df[(df['dept']=='IT') & (df['age']<30)])

   emp_id name  age  salary dept
2       3    C   28   40000   IT

## Question 2
### Demonstrate sorting:
#### Sort by `salary` ascending.
#### Sort by `dept` ascending and `salary` descending.

In [17]:
df=df.sort_values(by='salary',ascending=True)
df

   emp_id name  age  salary   dept
4       5    E   24   28000     HR
0       1    A   25   30000     HR
2       3    C   28   40000     IT
3       4    D   29   45000  Sales
1       2    B   32   50000     IT
5       6    F   35   60000     IT

In [19]:
df=df.sort_values(by=['dept','salary'],ascending=[True,False])
df

   emp_id name  age  salary   dept
0       1    A   25   30000     HR
4       5    E   24   28000     HR
5       6    F   35   60000     IT
1       2    B   32   50000     IT
2       3    C   28   40000     IT
3       4    D   29   45000  Sales

## Question 3
### Create a DataFrame with missing values in both numeric and string columns.
#### Detect missing values.
#### Count missing values per column.

In [35]:
df2 = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': ['x', None, 'z']
})

In [22]:
df2.isna()

       A      B
0  False  False
1   True   True
2  False  False

In [24]:
df2.isna().sum()

A    1
B    1
dtype: int64

## Question 4
### Handle missing values:
#### Drop rows with any missing value.
#### Fill missing numeric values with column mean and string values with `"Unknown"`.

In [27]:
data=df2.dropna(axis=1)
data

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [36]:
filter=df2['A'].fillna(df2['A'].mean())
filter

0    1.0
1    2.0
2    3.0
Name: A, dtype: float64

In [38]:
filtered=df2['B'].fillna('Unknown')
filtered

0          x
1    Unknown
2          z
Name: B, dtype: object

## Question 5
### Create a DataFrame with column `score`.
#### Replace scores < 35 with 35.
#### Replace scores > 90 with 90.

In [39]:
df = pd.DataFrame({'score': [20, 40, 95, 88]})
df['score'] = df['score'].clip(lower=35, upper=90)
print(df)

   score
0     35
1     40
2     90
3     88

## Question 6
### Use `.query()` to filter rows where `salary > 45000` and `dept == "IT"`.
#### Achieve the same using boolean indexing.

In [51]:
print(df.query('salary>45000 and dept=="IT"'))

   emp_id name  age  salary dept
1       2    B   32   50000   IT
5       6    F   35   60000   IT

In [53]:
print(df[(df['salary']>45000) & (df['dept']=='IT')])

   emp_id name  age  salary dept
1       2    B   32   50000   IT
5       6    F   35   60000   IT

## Question 7
### Use `.isin()` to filter rows where `dept` is in `['IT', 'HR']`.

In [56]:
print(df['dept'].isin(['IT','HR']))

0     True
1     True
2     True
3    False
4     True
5     True
Name: dept, dtype: bool

## Question 8
### Create a DataFrame with duplicate `emp_id`.
#### Use `.drop_duplicates` on `emp_id` with `keep='first'` and `keep='last'`.

In [60]:
df3 = pd.DataFrame({'emp_id': [1, 2, 3, 4, 5, 6, 5, 4, 6],'name': ['A', 'B', 'C', 'D', 'E', 'F','G','H','I']})

In [62]:
df3.drop_duplicates(subset='emp_id',keep='first')

   emp_id name
0       1    A
1       2    B
2       3    C
3       4    D
4       5    E
5       6    F

In [63]:
df3.drop_duplicates(subset='emp_id',keep='last')

   emp_id name
0       1    A
1       2    B
2       3    C
6       5    G
7       4    H
8       6    I

## Question 9
### Create a DataFrame with a categorical-like column (`"Low"`, `"Medium"`, `"High"`).
#### Convert it to `category` dtype and display categories.

In [70]:
df=pd.DataFrame({'level':['Low','Medium','High','Low','High']})
df

    level
0     Low
1  Medium
2    High
3     Low
4    High

In [72]:
df['level']=df['level'].astype('category')
df

    level
0     Low
1  Medium
2    High
3     Low
4    High

In [73]:
df['level'].cat.categories

Index(['High', 'Low', 'Medium'], dtype='object')

## Question 10
### Create a DataFrame with 2 numeric columns.
#### Use `.clip` to keep values between 10 and 50.

In [74]:
df = pd.DataFrame({'x': [5, 20, 60], 'y': [0, 30, 100]})
df.clip(lower=10,upper=50)

    x   y
0  10  10
1  20  30
2  50  50