# Day 7 – GroupBy & Aggregation: 10 Questions

## Question 1
### Create a sales DataFrame with columns: `region`, `product`, `units`, `price`.
#### Add `revenue = units * price`.
#### Group by `region` to find total revenue per region.

In [2]:
import numpy as np
import pandas as pd

In [20]:
df = pd.DataFrame({
    'region': ['North', 'South', 'East', 'West'],
    'product': ['A', 'B', 'C', 'D'],
    'units': [10, 20, 15, 5],
    'price': [100, 300, 200, 150]})

In [21]:
df['revenue']=df['units']*df['price']

In [22]:
df

  region product  units  price  revenue
0  North       A     10    100     1000
1  South       B     20    300     6000
2   East       C     15    200     3000
3   West       D      5    150      750

In [23]:
data=df.groupby('region')['revenue'].sum()

In [24]:
data

region
East     3000
North    1000
South    6000
West      750
Name: revenue, dtype: int64

## Question 2
### Group the same DataFrame by `product` and compute:
#### Total units sold.
#### Average price.

In [25]:
data_pro=df.groupby('product')['units'].sum()
data_pro

product
A    10
B    20
C    15
D     5
Name: units, dtype: int64

In [26]:
data_avg=df.groupby('product')['price'].mean()
data_avg

product
A    100.0
B    300.0
C    200.0
D    150.0
Name: price, dtype: float64

## Question 3
### Create a student DataFrame: `class`, `student`, `marks`.
#### Group by `class` and find mean and max marks.

In [31]:
df4 = pd.DataFrame({
    'class': ['X', 'X', 'Y', 'Y'],
    'student': ['A', 'B', 'C', 'D'],
    'marks': [80, 90, 70, 75]})

In [32]:
df4.groupby('class')['marks'].mean()

class
X    85.0
Y    72.5
Name: marks, dtype: float64

In [33]:
df4.groupby('class')['marks'].max()

class
X    90
Y    75
Name: marks, dtype: int64

## Question 4
### Use `.agg()` to calculate `min`, `max`, `mean`, `count` for `marks` per `class`.

In [34]:
stats=df4.groupby('class')['marks'].agg(['min','max','mean','count'])

In [35]:
stats

       min  max  mean  count
class
X       80   90  85.0      2
Y       70   75  72.5      2

## Question 5
### Create a DataFrame with `category`, `sub_category`, `value`.
#### Group by both columns and calculate sum of `value`.
#### Reset index.

In [36]:
df_cat = pd.DataFrame({
    'category': ['Cat1', 'Cat1', 'Cat2'],
    'sub_category': ['S1', 'S2', 'S1'],
    'value': [10, 20, 30]
})

In [37]:
df_cat

  category sub_category  value
0     Cat1           S1     10
1     Cat1           S2     20
2     Cat2           S1     30

In [39]:
df_cat.groupby(['category','sub_category'])['value'].sum().reset_index()

  category sub_category  value
0     Cat1           S1     10
1     Cat1           S2     20
2     Cat2           S1     30

## Question 6
### Create `customer_id`, `order_id`, `amount` DataFrame.
#### Group by `customer_id` to get total and average `amount`.
#### Sort by total amount descending.

In [40]:
orders = pd.DataFrame({
    'customer_id': [1, 1, 2, 3],
    'order_id': [101, 102, 103, 104],
    'amount': [100, 150, 200, 300]
})

In [41]:
orders

   customer_id  order_id  amount
0            1       101     100
1            1       102     150
2            2       103     200
3            3       104     300

In [49]:
g=orders.groupby('customer_id')['amount'].agg(['sum','mean'])
g

             sum   mean
customer_id
1            250  125.0
2            200  200.0
3            300  300.0

In [51]:
sort=g.sort_values('sum',ascending=False)
sort

             sum   mean
customer_id
3            300  300.0
1            250  125.0
2            200  200.0

## Question 7
#### Use `value_counts()` on a categorical column and convert result to DataFrame with columns `value`, `count`.

In [57]:
df5 = pd.DataFrame({
    "priority": ["Low", "Medium", "High", "Low", "High", "Low"]})
df5

  priority
0      Low
1   Medium
2     High
3      Low
4     High
5      Low

In [60]:
counts_df = df5["priority"].value_counts().reset_index()
counts_df

  priority  count
0      Low      3
1     High      2
2   Medium      1

## Question 8
### Create a DataFrame with a `date` column and `sales`.
#### Convert `date` to datetime.
#### Group by month and sum sales.

In [61]:
d = pd.DataFrame({
    'date': ['2025-01-01', '2025-01-10', '2025-02-05'],
    'sales': [100, 200, 300]
})

In [66]:
d['date']=pd.to_datetime(d['date'])
d['date']

0   2025-01-01
1   2025-01-10
2   2025-02-05
Name: date, dtype: datetime64[ns]

In [67]:
d['month']=d['date'].dt.to_period('M')

In [68]:
d

        date  sales    month
0 2025-01-01    100  2025-01
1 2025-01-10    200  2025-01
2 2025-02-05    300  2025-02

In [69]:
res=d.groupby('month')['sales'].sum()

In [70]:
res

month
2025-01    300
2025-02    300
Freq: M, Name: sales, dtype: int64

## Question 9
### Create `team`, `player`, `score` DataFrame.
#### Find player with highest score in each team (using `idxmax`).

In [71]:
df = pd.DataFrame({
    "team": ["A", "A", "B", "B", "C", "C"],
    "player": ["P1", "P2", "P3", "P4", "P5", "P6"],
    "score": [50, 80, 60, 90, 70, 85]
})

In [72]:
df

  team player  score
0    A     P1     50
1    A     P2     80
2    B     P3     60
3    B     P4     90
4    C     P5     70
5    C     P6     85

In [75]:
t=df.groupby('team')['score'].idxmax()
t

team
A    1
B    3
C    5
Name: score, dtype: int64

In [77]:
best=df.loc[t]
best

  team player  score
1    A     P2     80
3    B     P4     90
5    C     P6     85

## Question 10
### Use `groupby` and `filter` to keep only groups where mean `marks` > 70.

In [80]:
mark=df4.groupby('class').filter(lambda x:x['marks'].mean()>70)

In [81]:
mark

  class student  marks
0     X       A     80
1     X       B     90
2     Y       C     70
3     Y       D     75